<?php

namespace App\Services\Visa;

use App\Contracts\Visa\VisaLookupProvider;
use App\Services\Visa\DTO\VisaDocument;
use App\Services\Visa\DTO\VisaExport;
use App\Services\Visa\Support\VisaRedactor;
use Barryvdh\DomPDF\Facade\Pdf;
use InvalidArgumentException;

/**
 * On-demand JetPakistan exports from official HTML document / structured fields.
 * Generated PDF/PNG are copies — not MOFA-issued application/pdf.
 */
final class VisaExportService
{
    public function __construct(
        private readonly VisaLookupProvider $provider,
        private readonly VisaLookupService $lookupService,
        private readonly VisaRedactor $redactor,
    ) {}

    public function document(string $lookupSessionId, string $documentRef): VisaDocument
    {
        $session = $this->lookupService->hydrateSession($lookupSessionId);

        return $this->provider->getDocument($session, $documentRef);
    }

    public function exportPdf(string $lookupSessionId, string $documentRef): VisaExport
    {
        $doc = $this->document($lookupSessionId, $documentRef);
        $fields = $this->fieldsFromSession($lookupSessionId, $documentRef);
        $pdf = Pdf::loadView('pdf.visa-document', [
            'fields' => $fields,
            'attribution' => 'Generated by JetPakistan from the official Saudi MOFA visa result page. Not a MOFA-issued PDF file.',
            'source' => 'Saudi Ministry of Foreign Affairs',
        ])->setPaper('a4');
        $bytes = $pdf->output();

        return new VisaExport(
            format: 'pdf',
            mimeType: 'application/pdf',
            bytes: $bytes,
            sha256: hash('sha256', $bytes),
            label: 'Visa PDF copy',
            attribution: 'Generated from official MOFA visa page.',
        );
    }

    public function exportPng(string $lookupSessionId, string $documentRef): VisaExport
    {
        $fields = $this->fieldsFromSession($lookupSessionId, $documentRef);
        if (! function_exists('imagecreatetruecolor')) {
            throw new InvalidArgumentException('PNG export requires GD.');
        }
        $width = 800;
        $height = 1100;
        $im = imagecreatetruecolor($width, $height);
        $white = imagecolorallocate($im, 255, 255, 255);
        $black = imagecolorallocate($im, 20, 20, 20);
        $muted = imagecolorallocate($im, 90, 90, 90);
        imagefilledrectangle($im, 0, 0, $width, $height, $white);
        imagestring($im, 5, 24, 24, 'Visa image copy', $black);
        imagestring($im, 3, 24, 48, 'Source: Saudi Ministry of Foreign Affairs', $muted);
        imagestring($im, 2, 24, 70, 'Not an official MOFA-issued image file', $muted);
        $y = 110;
        foreach ($fields as $key => $value) {
            if ($value === null || $value === '') {
                continue;
            }
            $line = $key.': '.$this->safeLine((string) $value);
            imagestring($im, 3, 24, $y, substr($line, 0, 90), $black);
            $y += 22;
            if ($y > $height - 40) {
                break;
            }
        }
        ob_start();
        imagepng($im);
        $bytes = (string) ob_get_clean();
        imagedestroy($im);

        return new VisaExport(
            format: 'png',
            mimeType: 'image/png',
            bytes: $bytes,
            sha256: hash('sha256', $bytes),
            label: 'Image copy of official visa document',
            attribution: 'Generated from official MOFA visa page.',
        );
    }

    /**
     * @return array<string, string|null>
     */
    private function fieldsFromSession(string $lookupSessionId, string $documentRef): array
    {
        $session = $this->lookupService->hydrateSession($lookupSessionId);
        $doc = $this->provider->getDocument($session, $documentRef);
        // Prefer structured fields from session state when present
        $row = app(VisaLookupSessionStore::class)->get($lookupSessionId, $session->ownerToken);
        $fields = $row['state']['document']['fields'] ?? null;
        if (is_array($fields)) {
            return $fields;
        }

        return ['document_sha256' => $doc->sha256];
    }

    private function safeLine(string $value): string
    {
        return preg_replace('/[^\x20-\x7E]/', '?', $value) ?? $value;
    }
}
