import type { ReadOnlyEndpointContract } from "@/types/read-only-integration";

const SHARED_EXCLUSIONS = [
  "password",
  "password_hash",
  "mfa_secret",
  "recovery_codes",
  "session_id",
  "csrf_token",
  "api_key",
  "supplier_credentials",
  "pcc",
  "lniata",
  "card_number",
  "passport_number",
];

export const READ_ONLY_ENDPOINT_CONTRACTS: ReadOnlyEndpointContract[] = [
  {
    module: "session",
    routeConcept: "GET /api/dashboard/session",
    method: "GET",
    queryParameters: [],
    pagination: false,
    filtering: false,
    sorting: false,
    authorization: "Authenticated Laravel session",
    sensitiveFieldExclusions: [...SHARED_EXCLUSIONS, "session_token"],
    cacheStaleBehavior: "No cache; session summary always fresh",
    fixtureEquivalent: "session-service / mockUser",
    implementationStatus: "architecture",
  },
  {
    module: "overview",
    routeConcept: "GET /api/dashboard/overview",
    method: "GET",
    queryParameters: ["referenceDate"],
    pagination: false,
    filtering: false,
    sorting: false,
    authorization: "dashboard.view",
    sensitiveFieldExclusions: SHARED_EXCLUSIONS,
    cacheStaleBehavior: "staleAfter 60s; show StaleDataNotice",
    fixtureEquivalent: "getOverviewData / overview-fixtures",
    implementationStatus: "fixture",
  },
  {
    module: "bookings",
    routeConcept: "GET /api/dashboard/bookings",
    method: "GET",
    queryParameters: ["page", "pageSize", "sort", "direction", "status", "channel", "search", "selectedId"],
    pagination: true,
    filtering: true,
    sorting: true,
    authorization: "bookings.view",
    sensitiveFieldExclusions: [...SHARED_EXCLUSIONS, "passenger_documents"],
    cacheStaleBehavior: "staleAfter 30s",
    fixtureEquivalent: "getBookingsPage / booking-fixtures",
    implementationStatus: "fixture",
  },
  {
    module: "payments",
    routeConcept: "GET /api/dashboard/payments",
    method: "GET",
    queryParameters: ["page", "pageSize", "sort", "status", "reconciliation", "search"],
    pagination: true,
    filtering: true,
    sorting: true,
    authorization: "payments.view",
    sensitiveFieldExclusions: [...SHARED_EXCLUSIONS, "card_number", "pan"],
    cacheStaleBehavior: "staleAfter 30s",
    fixtureEquivalent: "payment-service / payment-fixtures",
    implementationStatus: "fixture",
  },
  {
    module: "customers",
    routeConcept: "GET /api/dashboard/customers",
    method: "GET",
    queryParameters: ["page", "pageSize", "status", "verification", "search"],
    pagination: true,
    filtering: true,
    sorting: true,
    authorization: "customers.view",
    sensitiveFieldExclusions: [...SHARED_EXCLUSIONS, "national_id"],
    cacheStaleBehavior: "staleAfter 60s",
    fixtureEquivalent: "customer-service / customer-fixtures",
    implementationStatus: "fixture",
  },
  {
    module: "suppliers",
    routeConcept: "GET /api/dashboard/suppliers",
    method: "GET",
    queryParameters: ["page", "status", "integration", "search"],
    pagination: true,
    filtering: true,
    sorting: true,
    authorization: "suppliers.view",
    sensitiveFieldExclusions: [...SHARED_EXCLUSIONS, "pcc", "lniata", "supplier_credentials"],
    cacheStaleBehavior: "staleAfter 120s",
    fixtureEquivalent: "supplier-service / supplier-fixtures",
    implementationStatus: "architecture",
  },
  {
    module: "agents",
    routeConcept: "GET /api/dashboard/agents",
    method: "GET",
    queryParameters: ["page", "status", "commercial", "search"],
    pagination: true,
    filtering: true,
    sorting: true,
    authorization: "agents.view",
    sensitiveFieldExclusions: SHARED_EXCLUSIONS,
    cacheStaleBehavior: "staleAfter 60s",
    fixtureEquivalent: "agent-service / agent-fixtures",
    implementationStatus: "architecture",
  },
  {
    module: "pnrs",
    routeConcept: "GET /api/dashboard/pnrs",
    method: "GET",
    queryParameters: ["page", "channel", "lifecycle", "search", "selected"],
    pagination: true,
    filtering: true,
    sorting: true,
    authorization: "pnrs.view",
    sensitiveFieldExclusions: SHARED_EXCLUSIONS,
    cacheStaleBehavior: "staleAfter 30s; GDS/NDC channel explicit",
    fixtureEquivalent: "pnr-service / pnr-fixtures",
    implementationStatus: "architecture",
  },
  {
    module: "tickets",
    routeConcept: "GET /api/dashboard/tickets",
    method: "GET",
    queryParameters: ["page", "issueStatus", "documentType", "search"],
    pagination: true,
    filtering: true,
    sorting: true,
    authorization: "tickets.view",
    sensitiveFieldExclusions: SHARED_EXCLUSIONS,
    cacheStaleBehavior: "staleAfter 30s",
    fixtureEquivalent: "ticket-service / ticket-fixtures",
    implementationStatus: "architecture",
  },
  {
    module: "reports",
    routeConcept: "GET /api/dashboard/reports/{section}",
    method: "GET",
    queryParameters: ["datePreset", "startDate", "endDate", "channel", "currency"],
    pagination: false,
    filtering: true,
    sorting: false,
    authorization: "reports.view",
    sensitiveFieldExclusions: SHARED_EXCLUSIONS,
    cacheStaleBehavior: "referenceTime explicit; staleAfter 300s",
    fixtureEquivalent: "report-service / report fixtures",
    implementationStatus: "architecture",
  },
  {
    module: "cms",
    routeConcept: "GET /api/dashboard/cms/{resource}",
    method: "GET",
    queryParameters: ["page", "status", "themeMode", "search", "selected"],
    pagination: true,
    filtering: true,
    sorting: true,
    authorization: "cms.view",
    sensitiveFieldExclusions: SHARED_EXCLUSIONS,
    cacheStaleBehavior: "staleAfter 120s",
    fixtureEquivalent: "cms-service / cms-fixtures",
    implementationStatus: "fixture",
  },
  {
    module: "users",
    routeConcept: "GET /api/dashboard/users",
    method: "GET",
    queryParameters: ["page", "status", "role", "department", "search", "selected"],
    pagination: true,
    filtering: true,
    sorting: true,
    authorization: "users.view",
    sensitiveFieldExclusions: [...SHARED_EXCLUSIONS, "mfa_secret"],
    cacheStaleBehavior: "staleAfter 60s",
    fixtureEquivalent: "user-service / user-fixtures",
    implementationStatus: "fixture",
  },
  {
    module: "roles",
    routeConcept: "GET /api/dashboard/roles",
    method: "GET",
    queryParameters: ["page", "search", "selected", "compare"],
    pagination: true,
    filtering: true,
    sorting: true,
    authorization: "roles.view",
    sensitiveFieldExclusions: SHARED_EXCLUSIONS,
    cacheStaleBehavior: "staleAfter 300s",
    fixtureEquivalent: "role-service / rbac-fixtures",
    implementationStatus: "fixture",
  },
  {
    module: "permissions",
    routeConcept: "GET /api/dashboard/permissions",
    method: "GET",
    queryParameters: ["domain", "risk", "search", "selected"],
    pagination: true,
    filtering: true,
    sorting: true,
    authorization: "permissions.view",
    sensitiveFieldExclusions: SHARED_EXCLUSIONS,
    cacheStaleBehavior: "staleAfter 300s",
    fixtureEquivalent: "permission-service / permission-catalog",
    implementationStatus: "fixture",
  },
  {
    module: "settings",
    routeConcept: "GET /api/dashboard/settings/{section}",
    method: "GET",
    queryParameters: ["section"],
    pagination: false,
    filtering: false,
    sorting: false,
    authorization: "settings.view",
    sensitiveFieldExclusions: [...SHARED_EXCLUSIONS, "integration_secrets"],
    cacheStaleBehavior: "staleAfter 300s; metadata only",
    fixtureEquivalent: "settings-service / settings-fixtures",
    implementationStatus: "fixture",
  },
  {
    module: "audit",
    routeConcept: "GET /api/dashboard/audit/events",
    method: "GET",
    queryParameters: ["page", "pageSize", "category", "datePreset", "search", "selected"],
    pagination: true,
    filtering: true,
    sorting: true,
    authorization: "audit.view",
    sensitiveFieldExclusions: [...SHARED_EXCLUSIONS, "raw_ip", "user_agent_full"],
    cacheStaleBehavior: "staleAfter 30s; sanitized actor metadata",
    fixtureEquivalent: "audit-service / audit-fixtures",
    implementationStatus: "fixture",
  },
];

export function getEndpointContract(module: ReadOnlyEndpointContract["module"]): ReadOnlyEndpointContract | undefined {
  return READ_ONLY_ENDPOINT_CONTRACTS.find((c) => c.module === module);
}
