import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["selector", '[data-theme="dark"]'],
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./features/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        jp: {
          brand: "var(--jp-brand)",
          "brand-hover": "var(--jp-brand-hover)",
          "brand-active": "var(--jp-brand-active)",
          "brand-soft": "var(--jp-brand-soft)",
          "brand-border": "var(--jp-brand-border)",
          primary: "var(--jp-primary)",
          "primary-hover": "var(--jp-primary-hover)",
          "primary-active": "var(--jp-primary-active)",
          "primary-soft": "var(--jp-primary-soft)",
          "primary-border": "var(--jp-primary-border)",
          accent: "var(--jp-accent)",
          "accent-hover": "var(--jp-accent-hover)",
          "accent-soft": "var(--jp-accent-soft)",
          bg: "var(--jp-bg)",
          "bg-subtle": "var(--jp-bg-subtle)",
          page: "var(--jp-page-bg)",
          surface: "var(--jp-surface)",
          "surface-raised": "var(--jp-surface-raised)",
          "surface-muted": "var(--jp-surface-muted)",
          "surface-inverse": "var(--jp-surface-inverse)",
          text: "var(--jp-text)",
          muted: "var(--jp-text-muted)",
          "text-muted": "var(--jp-text-muted)",
          subtle: "var(--jp-text-subtle)",
          border: "var(--jp-border)",
          "border-strong": "var(--jp-border-strong)",
          "border-soft": "var(--jp-border-soft)",
          focus: "var(--jp-focus)",
          success: "var(--jp-success)",
          "success-soft": "var(--jp-success-soft)",
          warning: "var(--jp-warning)",
          "warning-soft": "var(--jp-warning-soft)",
          danger: "var(--jp-danger)",
          "danger-soft": "var(--jp-danger-soft)",
          info: "var(--jp-info)",
          "info-soft": "var(--jp-info-soft)",
          overlay: "var(--jp-overlay)",
          skeleton: "var(--jp-skeleton)",
          "skeleton-highlight": "var(--jp-skeleton-highlight)",
          footer: "var(--jp-footer-bg)",
        },
      },
      fontFamily: {
        sans: ["var(--jp-font-sans)"],
        display: ["var(--jp-font-display)"],
        mono: ["var(--jp-font-mono)"],
      },
      fontSize: {
        "jp-xs": ["var(--jp-text-xs)", { lineHeight: "var(--jp-leading-normal)" }],
        "jp-sm": ["var(--jp-text-sm)", { lineHeight: "var(--jp-leading-normal)" }],
        "jp-body": ["var(--jp-text-base)", { lineHeight: "var(--jp-leading-normal)" }],
        "jp-base": ["var(--jp-text-base)", { lineHeight: "var(--jp-leading-normal)" }],
        "jp-md": ["var(--jp-text-lg)", { lineHeight: "var(--jp-leading-snug)" }],
        "jp-lg": ["var(--jp-text-xl)", { lineHeight: "var(--jp-leading-snug)" }],
        "jp-xl": ["var(--jp-heading-md)", { lineHeight: "var(--jp-leading-tight)" }],
        "jp-h3": ["var(--jp-heading-sm)", { lineHeight: "var(--jp-leading-snug)" }],
        "jp-h2": ["var(--jp-heading-lg)", { lineHeight: "var(--jp-leading-tight)" }],
        "jp-h1": ["var(--jp-heading-xl)", { lineHeight: "var(--jp-leading-tight)" }],
      },
      spacing: {
        "jp-2xs": "var(--jp-space-2xs)",
        "jp-xs": "var(--jp-space-xs)",
        "jp-sm": "var(--jp-space-sm)",
        "jp-md": "var(--jp-space-md)",
        "jp-lg": "var(--jp-space-lg)",
        "jp-xl": "var(--jp-space-xl)",
        "jp-2xl": "var(--jp-space-2xl)",
        "jp-3xl": "var(--jp-space-3xl)",
        "jp-4xl": "var(--jp-space-4xl)",
        "jp-5xl": "var(--jp-space-5xl)",
      },
      borderRadius: {
        "jp-sm": "var(--jp-radius-sm)",
        "jp-md": "var(--jp-radius-md)",
        "jp-lg": "var(--jp-radius-lg)",
        "jp-xl": "var(--jp-radius-xl)",
        "jp-pill": "var(--jp-radius-pill)",
        "jp-button": "var(--jp-button-radius)",
        "jp-card": "var(--jp-card-radius)",
      },
      boxShadow: {
        "jp-sm": "var(--jp-shadow-sm)",
        "jp-md": "var(--jp-shadow-md)",
        "jp-card": "var(--jp-shadow-card)",
        "jp-raised": "var(--jp-shadow-raised)",
        "jp-focus": "var(--jp-focus-ring)",
      },
      maxWidth: {
        "jp-container": "var(--jp-maxw)",
        "jp-narrow": "var(--jp-maxw-narrow)",
        "jp-booking": "var(--jp-maxw-booking)",
      },
      height: {
        "jp-nav": "var(--jp-nav-height)",
        "jp-nav-mobile": "var(--jp-nav-height-mobile)",
        "jp-button": "var(--jp-button-height)",
        "jp-control": "var(--jp-control-height)",
      },
      minHeight: {
        "jp-button": "var(--jp-button-height)",
        "jp-control": "var(--jp-control-height)",
        "jp-tap": "44px",
      },
      transitionDuration: {
        "jp-fast": "var(--jp-motion-fast)",
        ui: "var(--jp-motion-fast)",
        "jp-standard": "var(--jp-motion-standard)",
        drawer: "var(--jp-motion-standard)",
        "jp-slow": "var(--jp-motion-slow)",
      },
      transitionTimingFunction: {
        "jp-standard": "var(--jp-ease-standard)",
        "jp-emphasized": "var(--jp-ease-emphasized)",
      },
      width: {
        "jp-sidebar": "var(--jp-sidebar-width)",
      },
    },
  },
  plugins: [],
};

export default config;
