<x-mail::message>
# Ticket Issued

Hello {{ $booking->contact?->meta['name'] ?? $booking->customer?->name ?? 'Customer' }},

@php
    $brandName = $booking->agency->agencySetting?->display_name ?: $booking->agency->name;
    $supportEmail = $booking->agency->agencySetting?->support_email ?: null;
    $supportPhone = $booking->agency->agencySetting?->support_phone ?: null;
@endphp

Your booking has been ticketed.

- Booking reference: **{{ $booking->reference_code }}**
- Route: **{{ $booking->route ?? 'N/A' }}**
- Travel date: **{{ $booking->travel_date?->format('d M Y') ?? 'N/A' }}**
- PNR: **{{ $booking->pnr ?? 'N/A' }}**
- Tickets: **{{ $booking->tickets->count() }}**

@if ($booking->tickets->isNotEmpty())
**Ticket numbers:**

@foreach ($booking->tickets as $ticket)
- {{ $ticket->ticket_number ?? 'N/A' }}@if(!empty($ticket->meta['passenger_name'])) ({{ $ticket->meta['passenger_name'] }})@endif
@endforeach
@endif

A full itinerary PDF may be sent separately when it is generated by our team.

Thanks,<br>
{{ $brandName }}

@if ($supportEmail || $supportPhone)
Support: {{ $supportEmail ?? 'N/A' }}{{ $supportPhone ? ' · '.$supportPhone : '' }}
@endif
</x-mail::message>
