<?php

namespace Tests\Unit\Support\Emails;

use App\Enums\OtaNotificationEvent;
use App\Models\Agency;
use App\Models\Booking;
use App\Support\Emails\OtaOperationalEmailRenderer;
use Database\Seeders\OtaFoundationSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Mail;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

class OtaOperationalEmailRendererTest extends TestCase
{
    use RefreshDatabase;

    #[Test]
    public function ops_email_includes_actionable_summary_layout(): void
    {
        Mail::fake();
        $this->seed(OtaFoundationSeeder::class);
        $agency = Agency::query()->where('slug', config('ota.default_agency_slug'))->firstOrFail();
        $booking = Booking::factory()->for($agency)->create([
            'route' => 'LHE — DXB',
        ]);

        $rendered = app(OtaOperationalEmailRenderer::class)->render(
            $agency,
            OtaNotificationEvent::BookingManualReviewRequired->value,
            [
                'booking_reference' => $booking->reference_code,
                'route' => 'LHE — DXB',
                'customer_name' => 'Jane Doe',
                'customer_email' => 'jane.doe@example.test',
                'customer_phone' => '+923001234567',
                'admin_booking_url' => 'https://example.test/admin/bookings/'.$booking->id,
                'review_reason' => 'Fare change requires staff review',
            ],
            'Manual review required',
            "Dear team,\nFare change requires staff review.\nBooking reference: ".$booking->reference_code,
            $booking,
        );

        $this->assertStringContainsString('Operational alert', $rendered->html);
        $this->assertStringContainsString('Action required', $rendered->html);
        $this->assertStringContainsString('Summary', $rendered->html);
        $this->assertStringContainsString('Open booking', $rendered->html);
        $this->assertStringContainsString('Fare change requires staff review', $rendered->html);
        $this->assertStringContainsString('Generated by OTA system.', $rendered->html);
        $this->assertStringNotContainsString('jane.doe@example.test', $rendered->html);
        $this->assertStringNotContainsString('923001234567', $rendered->html);
        $this->assertStringNotContainsString('{{', $rendered->html);
        Mail::assertNothingSent();
    }

    #[Test]
    public function ops_email_blocks_raw_supplier_payload_keys(): void
    {
        Mail::fake();
        $this->seed(OtaFoundationSeeder::class);
        $agency = Agency::query()->where('slug', config('ota.default_agency_slug'))->firstOrFail();

        $rendered = app(OtaOperationalEmailRenderer::class)->render(
            $agency,
            OtaNotificationEvent::SupplierBookingFailed->value,
            [
                'booking_reference' => 'OTA-BK-TEST-001',
                'supplier_response' => 'Bearer secret-token-value',
                'raw_payload' => '{"pcc":"ABC1"}',
                'supplier_error' => 'GDS timeout',
            ],
            'Supplier booking failed',
            'Supplier booking failed for OTA-BK-TEST-001.',
        );

        $this->assertStringNotContainsString('Bearer secret-token-value', $rendered->html);
        $this->assertStringNotContainsString('raw_payload', strtolower($rendered->html));
        $this->assertStringNotContainsString('supplier_response', strtolower($rendered->html));
        $this->assertStringNotContainsString('{{', $rendered->html);
        Mail::assertNothingSent();
    }
}
