<?php

return [
    'providers' => [
        'iati' => [
            'fields' => [
                'auth_code' => [
                    'label' => 'Auth Code',
                    'type' => 'text',
                    'required' => true,
                    'placeholder' => 'IATI auth code',
                    'help' => 'IATI auth code. Used as Bearer for /test/ping; paired with Secret for JWT exchange on flight API calls.',
                ],
                'secret' => [
                    'label' => 'Secret',
                    'type' => 'password',
                    'required' => false,
                    'placeholder' => 'Leave blank to keep existing value.',
                    'help' => 'Required for flight search/booking: exchanged with auth code via GET /rest/auth/token for JWT Bearer on flight v2 endpoints.',
                ],
                'organization_id' => [
                    'label' => 'Organization ID / Agency ID',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'e.g. 187570',
                    'help' => 'Optional IATI organization / agency identifier (sent as Organization-Id header when set).',
                ],
            ],
        ],
        'duffel' => [
            'fields' => [
                'access_token' => [
                    'label' => 'Access Token',
                    'type' => 'password',
                    'required' => true,
                    'placeholder' => 'duffel_test_...',
                    'help' => 'Paste your Duffel test access token. Keep environment as sandbox/test.',
                ],
                'api_version' => [
                    'label' => 'API Version',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'v2',
                    'default' => 'v2',
                ],
            ],
        ],
        'sabre' => [
            'fields' => [
                'sign_in' => [
                    'label' => 'Sabre Sign in / Client ID (EPR)',
                    'type' => 'text',
                    'required' => true,
                    'placeholder' => 'Leave blank to keep existing value.',
                    'help' => 'Your Sabre EPR / sign-in / OAuth client ID.',
                ],
                'password' => [
                    'label' => 'Sabre Secret / Password',
                    'type' => 'password',
                    'required' => true,
                    'placeholder' => 'Leave blank to keep existing value.',
                    'help' => 'Sabre password or OAuth client secret.',
                ],
                'pcc' => [
                    'label' => 'PCC (pseudo city code)',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'Leave blank to keep existing value.',
                ],
            ],
        ],
        'pia_ndc' => [
            'fields' => [
                'username' => [
                    'label' => 'Username',
                    'type' => 'text',
                    'required' => true,
                    'placeholder' => 'PIA NDC gateway username',
                ],
                'password' => [
                    'label' => 'Password',
                    'type' => 'password',
                    'required' => true,
                    'placeholder' => 'Leave blank to keep existing value.',
                ],
                'agency_id' => [
                    'label' => 'Agency ID',
                    'type' => 'text',
                    'required' => true,
                    'placeholder' => 'e.g. SELENS',
                ],
                'agency_name' => [
                    'label' => 'Agency Name',
                    'type' => 'text',
                    'required' => true,
                    'placeholder' => 'PIA NDC / Hitit gateway name',
                ],
                'owner_code' => [
                    'label' => 'Owner Code',
                    'type' => 'text',
                    'required' => true,
                    'placeholder' => 'Airline owner code from PIA',
                ],
                'carrier_code' => [
                    'label' => 'Carrier Code',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'PK',
                    'default' => 'PK',
                ],
                'currency' => [
                    'label' => 'Currency',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'PKR',
                    'default' => 'PKR',
                ],
                'language_code' => [
                    'label' => 'Language',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'EN',
                    'default' => 'EN',
                ],
                'mco_invoice_number' => [
                    'label' => 'MCO / Invoice Number',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'INV4000007708',
                    'help' => 'Required for ticketing and order change (MCO payment). Not required for search.',
                ],
                'payment_type' => [
                    'label' => 'Payment Type',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'MCO',
                    'default' => 'MCO',
                ],
            ],
        ],
        'airblue' => [
            'fields' => [
                'client_id' => [
                    'label' => 'Client ID',
                    'type' => 'text',
                    'required' => true,
                    'placeholder' => 'Zapways API client ID',
                ],
                'client_key' => [
                    'label' => 'Client Key',
                    'type' => 'password',
                    'required' => true,
                    'placeholder' => 'Leave blank to keep existing value.',
                ],
                'agent_id' => [
                    'label' => 'Agent ID',
                    'type' => 'text',
                    'required' => true,
                    'placeholder' => 'RequestorID ID',
                ],
                'agent_password' => [
                    'label' => 'Agent Password',
                    'type' => 'password',
                    'required' => true,
                    'placeholder' => 'Leave blank to keep existing value.',
                ],
            ],
        ],
        'one_api' => [
            'fields' => [
                'username' => [
                    'label' => 'API Username',
                    'type' => 'text',
                    'required' => true,
                    'placeholder' => 'ONE_API_TEST_USERNAME',
                ],
                'password' => [
                    'label' => 'API Password',
                    'type' => 'password',
                    'required' => true,
                    'placeholder' => 'Leave blank to keep existing value.',
                ],
                'agent_code' => [
                    'label' => 'Agent Code',
                    'type' => 'text',
                    'required' => true,
                    'placeholder' => 'ONE_API_TEST_AGENT',
                ],
                'agent_preferred_currency' => [
                    'label' => 'Agent Preferred Currency',
                    'type' => 'text',
                    'required' => true,
                    'placeholder' => 'AED',
                    'default' => 'AED',
                ],
                'pos_country' => [
                    'label' => 'POS Country',
                    'type' => 'text',
                    'required' => true,
                    'placeholder' => 'AE',
                ],
                'pos_station' => [
                    'label' => 'POS Station',
                    'type' => 'text',
                    'required' => true,
                    'placeholder' => 'DXB',
                ],
                'sales_channel' => [
                    'label' => 'Sales Channel',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'OTA',
                    'default' => 'OTA',
                ],
                'terminal_id' => [
                    'label' => 'Terminal ID',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'Configurable terminal',
                ],
                'rest_auth_url' => [
                    'label' => 'REST Auth URL',
                    'type' => 'text',
                    'required' => true,
                    'help' => 'JSON authenticate endpoint (not hard-coded in code).',
                ],
                'rest_search_url' => [
                    'label' => 'REST Search URL',
                    'type' => 'text',
                    'required' => true,
                    'help' => 'findOndWiseFlightCombinations endpoint.',
                ],
                'soap_url' => [
                    'label' => 'SOAP URL',
                    'type' => 'text',
                    'required' => false,
                    'help' => 'Mandatory for price/book; leave empty until vendor supplies endpoint.',
                ],
                'soap_action_price' => ['label' => 'SOAPAction Price (optional)', 'type' => 'text', 'required' => false],
                'soap_action_baggage' => ['label' => 'SOAPAction Baggage (optional)', 'type' => 'text', 'required' => false],
                'soap_action_meal' => ['label' => 'SOAPAction Meal (optional)', 'type' => 'text', 'required' => false],
                'soap_action_seat_map' => ['label' => 'SOAPAction Seat Map (optional)', 'type' => 'text', 'required' => false],
                'soap_action_book' => ['label' => 'SOAPAction Book (optional)', 'type' => 'text', 'required' => false],
                'soap_action_read' => ['label' => 'SOAPAction Read (optional)', 'type' => 'text', 'required' => false],
                'soap_action_modify' => ['label' => 'SOAPAction Modify (optional)', 'type' => 'text', 'required' => false],
                'connect_timeout_seconds' => ['label' => 'Connect Timeout (seconds)', 'type' => 'text', 'required' => false, 'default' => '10'],
                'request_timeout_seconds' => ['label' => 'Request Timeout (seconds)', 'type' => 'text', 'required' => false, 'default' => '60'],
                'search_timeout_seconds' => ['label' => 'Search Timeout (seconds)', 'type' => 'text', 'required' => false, 'default' => '90'],
                'verify_tls' => ['label' => 'Verify TLS', 'type' => 'text', 'required' => false, 'default' => 'true'],
                'carrier_allowlist' => [
                    'label' => 'Carrier Allowlist (comma-separated IATA)',
                    'type' => 'text',
                    'required' => false,
                    'help' => 'e.g. G9,3L — empty allows configured marketing carriers only when set in settings.',
                ],
                'marketing_carrier_allowlist' => ['label' => 'Marketing Carrier Allowlist', 'type' => 'text', 'required' => false],
                'operating_carrier_allowlist' => ['label' => 'Operating Carrier Allowlist', 'type' => 'text', 'required' => false],
                'allow_interline' => ['label' => 'Allow Interline', 'type' => 'text', 'required' => false, 'default' => 'false'],
                'on_hold_enabled' => ['label' => 'On-Hold Booking Enabled', 'type' => 'text', 'required' => false, 'default' => 'false'],
                'hold_payment_enabled' => ['label' => 'Hold Payment Enabled', 'type' => 'text', 'required' => false, 'default' => 'false'],
                'direct_bill_enabled' => ['label' => 'DirectBill Enabled', 'type' => 'text', 'required' => false, 'default' => 'true'],
                'live_search_enabled' => ['label' => 'Live Search Enabled', 'type' => 'text', 'required' => false, 'default' => 'false'],
                'live_booking_enabled' => ['label' => 'Live Booking Enabled', 'type' => 'text', 'required' => false, 'default' => 'false'],
                'live_payment_modification_enabled' => ['label' => 'Live Payment Modification Enabled', 'type' => 'text', 'required' => false, 'default' => 'false'],
                'max_search_results' => ['label' => 'Max Search Results', 'type' => 'text', 'required' => false, 'default' => '200'],
                'log_payloads' => ['label' => 'Log Payloads', 'type' => 'text', 'required' => false, 'default' => 'false'],
                'health_check_route' => ['label' => 'Health Check Route', 'type' => 'text', 'required' => false],
                'notes' => ['label' => 'Notes', 'type' => 'text', 'required' => false],
            ],
        ],
        'al_haider' => [
            'fields' => [
                'auth_mode' => [
                    'label' => 'Authentication mode',
                    'type' => 'select',
                    'required' => true,
                    'options' => [
                        'manual_token' => 'Manual bearer token',
                        'managed_token' => 'Managed token (admin supplies)',
                        'credentials_auto_token' => 'Username/password (auto login)',
                    ],
                    'default' => 'manual_token',
                    'help' => 'Manual uses a pasted bearer token. Managed keeps a token you supply. Auto logs in with username/password.',
                ],
                'existing_token' => [
                    'label' => 'Bearer token',
                    'type' => 'password',
                    'required' => false,
                    'placeholder' => 'Leave blank to keep existing value.',
                    'help' => 'Required for manual/managed modes unless switching to auto login.',
                ],
                'token_expires_at' => [
                    'label' => 'Token expires at',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'ISO-8601 or blank to derive from JWT',
                ],
                'username' => [
                    'label' => 'Username',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'Used for auto login or managed renewal',
                ],
                'password' => [
                    'label' => 'Password',
                    'type' => 'password',
                    'required' => false,
                    'placeholder' => 'Leave blank to keep existing value.',
                ],
                'auto_renew' => [
                    'label' => 'Auto renew managed token',
                    'type' => 'select',
                    'required' => false,
                    'options' => [
                        '0' => 'Disabled',
                        '1' => 'Enabled',
                    ],
                    'default' => '0',
                ],
            ],
        ],
        'ameer_e_millat' => [
            'fields' => [
                'auth_mode' => [
                    'label' => 'Authentication mode',
                    'type' => 'select',
                    'required' => true,
                    'options' => [
                        'manual_token' => 'Manual bearer token',
                        'managed_token' => 'Managed token (admin supplies)',
                        'credentials_auto_token' => 'Email/password (auto login)',
                    ],
                    'default' => 'manual_token',
                    'help' => 'Manual uses a pasted bearer token. Managed keeps a token you supply. Auto logs in with email/password.',
                ],
                'existing_token' => [
                    'label' => 'Bearer token',
                    'type' => 'password',
                    'required' => false,
                    'placeholder' => 'Leave blank to keep existing value.',
                    'help' => 'Required for manual/managed modes unless switching to auto login.',
                ],
                'token_expires_at' => [
                    'label' => 'Token expires at',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'ISO-8601 or blank to derive from JWT',
                ],
                'email' => [
                    'label' => 'Email',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'Login email for auto mode',
                ],
                'username' => [
                    'label' => 'Username',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'Optional alias for email',
                ],
                'password' => [
                    'label' => 'Password',
                    'type' => 'password',
                    'required' => false,
                    'placeholder' => 'Leave blank to keep existing value.',
                ],
                'auto_renew' => [
                    'label' => 'Auto renew managed token',
                    'type' => 'select',
                    'required' => false,
                    'options' => [
                        '0' => 'Disabled',
                        '1' => 'Enabled',
                    ],
                    'default' => '0',
                ],
            ],
        ],
    ],
];
