<?php

return [
    'providers' => [
        'iati' => [
            'fields' => [
                'auth_code' => [
                    'label' => 'Auth Code',
                    'type' => 'text',
                    'required' => true,
                    'placeholder' => 'IATI auth code',
                    'help' => 'IATI auth code. Used as Bearer for /test/ping; paired with Secret for JWT exchange on flight API calls.',
                ],
                'secret' => [
                    'label' => 'Secret',
                    'type' => 'password',
                    'required' => false,
                    'placeholder' => 'Leave blank to keep existing value.',
                    'help' => 'Required for flight search/booking: exchanged with auth code via GET /rest/auth/token for JWT Bearer on flight v2 endpoints.',
                ],
                'organization_id' => [
                    'label' => 'Organization ID / Agency ID',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'e.g. 187570',
                    'help' => 'Optional IATI organization / agency identifier (sent as Organization-Id header when set).',
                ],
            ],
        ],
        'duffel' => [
            'fields' => [
                'access_token' => [
                    'label' => 'Access Token',
                    'type' => 'password',
                    'required' => true,
                    'placeholder' => 'duffel_test_...',
                    'help' => 'Paste your Duffel test access token. Keep environment as sandbox/test.',
                ],
                'api_version' => [
                    'label' => 'API Version',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'v2',
                    'default' => 'v2',
                ],
            ],
        ],
        'sabre' => [
            'fields' => [
                'sign_in' => [
                    'label' => 'Sabre Sign in / Client ID (EPR)',
                    'type' => 'text',
                    'required' => true,
                    'placeholder' => 'Leave blank to keep existing value.',
                    'help' => 'Your Sabre EPR / sign-in / OAuth client ID.',
                ],
                'password' => [
                    'label' => 'Sabre Secret / Password',
                    'type' => 'password',
                    'required' => true,
                    'placeholder' => 'Leave blank to keep existing value.',
                    'help' => 'Sabre password or OAuth client secret.',
                ],
                'pcc' => [
                    'label' => 'PCC (pseudo city code)',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'Leave blank to keep existing value.',
                ],
            ],
        ],
        'pia_ndc' => [
            'fields' => [
                'username' => [
                    'label' => 'Username',
                    'type' => 'text',
                    'required' => true,
                    'placeholder' => 'PIA NDC gateway username',
                ],
                'password' => [
                    'label' => 'Password',
                    'type' => 'password',
                    'required' => true,
                    'placeholder' => 'Leave blank to keep existing value.',
                ],
                'agency_id' => [
                    'label' => 'Agency ID',
                    'type' => 'text',
                    'required' => true,
                    'placeholder' => 'e.g. SELENS',
                ],
                'agency_name' => [
                    'label' => 'Agency Name',
                    'type' => 'text',
                    'required' => true,
                    'placeholder' => 'PIA NDC / Hitit gateway name',
                ],
                'owner_code' => [
                    'label' => 'Owner Code',
                    'type' => 'text',
                    'required' => true,
                    'placeholder' => 'Airline owner code from PIA',
                ],
                'carrier_code' => [
                    'label' => 'Carrier Code',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'PK',
                    'default' => 'PK',
                ],
                'currency' => [
                    'label' => 'Currency',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'PKR',
                    'default' => 'PKR',
                ],
                'language_code' => [
                    'label' => 'Language',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'EN',
                    'default' => 'EN',
                ],
                'mco_invoice_number' => [
                    'label' => 'MCO / Invoice Number',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'INV4000007708',
                    'help' => 'Required for ticketing and order change (MCO payment). Not required for search.',
                ],
                'payment_type' => [
                    'label' => 'Payment Type',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'MCO',
                    'default' => 'MCO',
                ],
            ],
        ],
        'airblue' => [
            'fields' => [
                'api_channel' => [
                    'label' => 'API Channel',
                    'type' => 'select',
                    'required' => true,
                    'options' => [
                        'crane_ndc' => 'Crane NDC',
                        'zapways_ota' => 'Zapways OTA',
                    ],
                    'default' => 'crane_ndc',
                ],
                'username' => [
                    'label' => 'Username',
                    'type' => 'text',
                    'required' => false,
                    'channel' => 'crane_ndc',
                    'placeholder' => 'Crane NDC gateway username',
                ],
                'password' => [
                    'label' => 'Password',
                    'type' => 'password',
                    'required' => false,
                    'channel' => 'crane_ndc',
                    'placeholder' => 'Leave blank to keep existing value.',
                ],
                'agency_id' => [
                    'label' => 'Agency ID',
                    'type' => 'text',
                    'required' => false,
                    'channel' => 'crane_ndc',
                    'placeholder' => 'Travel agency ID',
                ],
                'agency_name' => [
                    'label' => 'Agency Name',
                    'type' => 'text',
                    'required' => false,
                    'channel' => 'crane_ndc',
                    'placeholder' => 'Travel agency name',
                ],
                'owner_code' => [
                    'label' => 'Owner Code',
                    'type' => 'text',
                    'required' => false,
                    'channel' => 'crane_ndc',
                    'placeholder' => 'Airline owner code',
                ],
                'carrier_code' => [
                    'label' => 'Carrier Code',
                    'type' => 'text',
                    'required' => false,
                    'channel' => 'crane_ndc',
                    'placeholder' => 'PA',
                    'default' => 'PA',
                ],
                'currency' => [
                    'label' => 'Currency',
                    'type' => 'text',
                    'required' => false,
                    'channel' => 'crane_ndc',
                    'placeholder' => 'PKR',
                    'default' => 'PKR',
                ],
                'language_code' => [
                    'label' => 'Language',
                    'type' => 'text',
                    'required' => false,
                    'channel' => 'crane_ndc',
                    'placeholder' => 'EN',
                    'default' => 'EN',
                ],
                'client_id' => [
                    'label' => 'Client ID',
                    'type' => 'text',
                    'required' => false,
                    'channel' => 'zapways_ota',
                    'placeholder' => 'Zapways API client ID',
                ],
                'client_key' => [
                    'label' => 'Client Key',
                    'type' => 'text',
                    'required' => false,
                    'channel' => 'zapways_ota',
                    'placeholder' => 'Zapways API client key',
                ],
                'agent_type' => [
                    'label' => 'Agent Type',
                    'type' => 'text',
                    'required' => false,
                    'channel' => 'zapways_ota',
                    'placeholder' => 'RequestorID Type',
                ],
                'agent_id' => [
                    'label' => 'Agent ID',
                    'type' => 'text',
                    'required' => false,
                    'channel' => 'zapways_ota',
                    'placeholder' => 'RequestorID ID',
                ],
                'agent_password' => [
                    'label' => 'Agent Password',
                    'type' => 'password',
                    'required' => false,
                    'channel' => 'zapways_ota',
                    'placeholder' => 'Leave blank to keep existing value.',
                ],
                'service_target' => [
                    'label' => 'Service Target',
                    'type' => 'text',
                    'required' => false,
                    'channel' => 'zapways_ota',
                    'placeholder' => 'Production',
                    'default' => 'Production',
                ],
                'service_version' => [
                    'label' => 'Service Version',
                    'type' => 'text',
                    'required' => false,
                    'channel' => 'zapways_ota',
                    'placeholder' => '1.04',
                    'default' => '1.04',
                ],
                'tls_cert_path' => [
                    'label' => 'TLS Certificate Path (optional)',
                    'type' => 'text',
                    'required' => false,
                    'channel' => 'zapways_ota',
                    'placeholder' => 'Server path to combined.pem',
                    'help' => 'Optional mutual TLS client certificate path on the application server.',
                ],
            ],
        ],
        'airline_direct' => [
            'fields' => [
                'api_key' => ['label' => 'API Key', 'type' => 'password', 'required' => false],
                'token' => ['label' => 'Token', 'type' => 'password', 'required' => false],
                'username' => ['label' => 'Username', 'type' => 'text', 'required' => false],
                'password' => ['label' => 'Password', 'type' => 'password', 'required' => false],
            ],
        ],
        'amadeus' => [
            'fields' => [
                'client_id' => ['label' => 'Client ID', 'type' => 'text', 'required' => true],
                'client_secret' => ['label' => 'Client Secret', 'type' => 'password', 'required' => true],
            ],
        ],
        'travelport' => [
            'fields' => [
                'client_id' => ['label' => 'Client ID', 'type' => 'text', 'required' => true],
                'client_secret' => ['label' => 'Client Secret', 'type' => 'password', 'required' => true],
            ],
        ],
    ],
];
