<?php

namespace App\Support\Emails;

use App\Models\Agency;
use App\Models\User;
use App\Support\Branding\CompanyEmailProfileResolver;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\View;

/**
 * Live send renderer for auth/registration emails (I8).
 */
class AuthEmailRenderer
{
    public function customerWelcome(User $user, string $brandName): CustomerFacingEmailRendered
    {
        $user->loadMissing('currentAgency.agencySetting');
        $profile = CompanyEmailProfileResolver::resolve($user->currentAgency);
        $name = trim((string) ($user->name ?? 'Customer')) ?: 'Customer';
        $cta = $this->loginCta();

        return $this->render(
            agency: $user->currentAgency,
            headline: 'Welcome to '.$brandName,
            intro: sprintf(
                'Hello %s, your customer account at %s was created successfully. Please verify your email address using the verification link we sent separately. The link expires in 24 hours.',
                $name,
                $brandName,
            ),
            details: [
                ['label' => 'Name', 'value' => $name],
                ['label' => 'Email', 'value' => (string) $user->email],
            ],
            ctaUrl: $cta['url'] ?? null,
            ctaLabel: $cta['label'] ?? null,
            footerDisclaimer: 'Please keep this email for your records.',
            statusBannerLabel: 'Welcome',
            statusBannerTone: 'success',
            nextSteps: [
                'Verify your email using the separate verification link.',
                'Sign in after verification to manage bookings.',
            ],
            plainBody: $this->plainLines([
                'Hello '.$name.',',
                '',
                'Your customer account at '.$brandName.' was created successfully.',
                '',
                'Please verify your email address using the verification link we sent separately.',
                'The link expires in 24 hours.',
                '',
                'If you did not create this account, please contact support.',
            ]),
        );
    }

    public function adminNewCustomerSignup(User $user, string $phone): CustomerFacingEmailRendered
    {
        $user->loadMissing('currentAgency.agencySetting');
        $profile = CompanyEmailProfileResolver::resolve($user->currentAgency);
        $name = trim((string) ($user->name ?? 'Customer')) ?: 'Customer';

        return $this->render(
            agency: $user->currentAgency,
            headline: 'New customer signup',
            intro: 'A new customer signed up on your platform.',
            details: [
                ['label' => 'Name', 'value' => $name],
                ['label' => 'Email', 'value' => ModernEmailLayout::maskEmail((string) $user->email)],
                ['label' => 'Contact / mobile', 'value' => ModernEmailLayout::maskPhone($phone)],
                ['label' => 'Signed up at', 'value' => now()->toDateTimeString()],
            ],
            ctaUrl: null,
            ctaLabel: null,
            emailMode: ModernEmailLayout::MODE_OPS,
            statusBannerLabel: 'New signup',
            statusBannerTone: 'info',
            actionCardTitle: 'What to do next',
            actionCardBody: 'Review the new customer account in the admin panel if follow-up is required.',
            footerDisclaimer: 'Generated by OTA system. No passwords or verification tokens are included.',
            plainBody: $this->plainLines([
                'A new customer signed up.',
                '',
                'Name: '.$name,
                'Email: '.$user->email,
                'Contact / mobile: '.$phone,
                'Signed up at: '.now()->toDateTimeString(),
            ]),
        );
    }

    public function loginOtp(User $user, string $brandName, string $otpCode, int $expiryMinutes): CustomerFacingEmailRendered
    {
        if ($this->usesJetpkEmailPackage()) {
            $user->loadMissing('currentAgency.agencySetting');

            return $this->renderJetpkEmail(
                type: 'otp',
                extra: [
                    'security' => [
                        'otp' => $otpCode,
                        'expiry_minutes' => $expiryMinutes,
                        'context' => 'Web sign-in',
                    ],
                    'otpCode' => $otpCode,
                    'otpExpiryMinutes' => $expiryMinutes,
                ],
                plainLines: [
                    'Hello '.(trim((string) ($user->name ?? 'Customer')) ?: 'Customer').',',
                    '',
                    'Your '.$brandName.' login verification code is: '.$otpCode,
                    '',
                    'This code expires in '.$expiryMinutes.' minutes.',
                    '',
                    'Never share this code with anyone.',
                ],
                agency: $user->currentAgency,
            );
        }

        $user->loadMissing('currentAgency.agencySetting');
        $name = trim((string) ($user->name ?? 'Customer')) ?: 'Customer';

        return $this->render(
            agency: $user->currentAgency,
            headline: 'Your login verification code',
            intro: sprintf(
                'Hello %s, use this one-time code to complete your sign-in to %s. The code expires in %d minutes.',
                $name,
                $brandName,
                $expiryMinutes,
            ),
            details: [
                ['label' => 'Verification code', 'value' => $otpCode],
                ['label' => 'Expires in', 'value' => $expiryMinutes.' minutes'],
            ],
            ctaUrl: null,
            ctaLabel: null,
            footerDisclaimer: 'Never share this code with anyone. '.$brandName.' staff will never ask for your OTP.',
            statusBannerLabel: 'Login verification',
            statusBannerTone: 'info',
            nextSteps: [
                'Enter the code on the verification screen to finish signing in.',
                'If you did not attempt to sign in, change your password and contact support.',
            ],
            plainBody: $this->plainLines([
                'Hello '.$name.',',
                '',
                'Your '.$brandName.' login verification code is: '.$otpCode,
                '',
                'This code expires in '.$expiryMinutes.' minutes.',
                '',
                'Never share this code with anyone.',
                'If you did not attempt to sign in, change your password and contact support.',
            ]),
        );
    }

    /**
     * @return array{url: string, label: string}|null
     */
    protected function loginCta(): ?array
    {
        if (Route::has('login')) {
            return [
                'url' => route('login', absolute: true),
                'label' => 'Sign in to your account',
            ];
        }

        return null;
    }

    protected function render(
        ?Agency $agency,
        string $headline,
        string $intro,
        array $details,
        ?string $ctaUrl,
        ?string $ctaLabel,
        string $footerDisclaimer,
        string $plainBody,
        string $emailMode = ModernEmailLayout::MODE_CUSTOMER,
        ?string $statusBannerLabel = null,
        string $statusBannerTone = 'info',
        ?string $actionCardTitle = null,
        ?string $actionCardBody = null,
        array $nextSteps = [],
    ): CustomerFacingEmailRendered {
        $profile = CompanyEmailProfileResolver::resolve($agency);
        $html = View::make('emails.layouts.modern', array_merge(
            ['companyEmailProfile' => $profile],
            ModernEmailLayout::viewData([
                'emailMode' => $emailMode,
                'headline' => $headline,
                'intro' => $intro,
                'statusBannerLabel' => $statusBannerLabel ?? $headline,
                'statusBannerTone' => $statusBannerTone,
                'actionCardTitle' => $actionCardTitle,
                'actionCardBody' => $actionCardBody,
                'contentHtml' => '',
                'details' => array_map(
                    fn (array $row): array => [
                        'label' => $row['label'],
                        'value' => e((string) ($row['value'] ?? '')),
                    ],
                    $details,
                ),
                'ctaUrl' => $ctaUrl,
                'ctaLabel' => $ctaLabel,
                'footerDisclaimer' => $footerDisclaimer,
                'nextSteps' => $nextSteps,
            ]),
        ))->render();

        return new CustomerFacingEmailRendered(
            html: $html,
            plainBody: $plainBody,
            profile: $profile,
        );
    }

    protected function usesJetpkEmailPackage(): bool
    {
        if ((string) config('ota_client.slug', '') === 'jetpk') {
            return true;
        }

        if (function_exists('ota_single_client_root_slug') && ota_single_client_root_slug() === 'jetpk') {
            return true;
        }

        return false;
    }

    /**
     * @param  array<string, mixed>  $extra
     * @param  list<string>  $plainLines
     */
    protected function renderJetpkEmail(string $type, array $extra, array $plainLines, ?Agency $agency = null): CustomerFacingEmailRendered
    {
        $eventKey = JetpkEmailViewResolver::eventKeyForType($type);
        if ($eventKey === null) {
            throw new \RuntimeException('JetPK email event missing for type: '.$type);
        }

        $result = app(JetpkEmailEventRenderer::class)->render(
            eventKey: $eventKey,
            agency: $agency,
            dbTemplate: null,
            runtimeVariables: [],
            payload: $extra,
        );

        return new CustomerFacingEmailRendered(
            html: $result->html,
            plainBody: $this->plainLines($plainLines),
            profile: CompanyEmailProfileResolver::resolveForPlatform(),
        );
    }

    /**
     * @param  list<string>  $lines
     */
    protected function plainLines(array $lines): string
    {
        return implode("\n", $lines);
    }
}
