<?php

namespace App\Support\Emails;

/**
 * Shared view data and safe display helpers for emails.layouts.modern (Email-H2).
 */
class ModernEmailLayout
{
    public const MODE_CUSTOMER = 'customer';

    public const MODE_OPS = 'ops';

    /** @var array<string, array{bg: string, border: string, text: string}> */
    public const STATUS_TONES = [
        'success' => ['bg' => '#ecfdf5', 'border' => '#10b981', 'text' => '#065f46'],
        'warning' => ['bg' => '#fffbeb', 'border' => '#f59e0b', 'text' => '#92400e'],
        'danger' => ['bg' => '#fef2f2', 'border' => '#ef4444', 'text' => '#991b1b'],
        'info' => ['bg' => '#eff6ff', 'border' => '#3b82f6', 'text' => '#1e40af'],
        'neutral' => ['bg' => '#f8fafc', 'border' => '#94a3b8', 'text' => '#475569'],
    ];

    /** @var list<string> */
    private const OPS_BLOCKED_DETAIL_KEYS = [
        'supplier_response',
        'raw_response',
        'raw_payload',
        'payload',
        'api_key',
        'token',
        'secret',
        'password',
        'smtp_password',
        'supplier_error',
        'gds_response',
        'cpnr',
        'pcc',
        'rbd',
    ];

    /** @var list<string> */
    private const OPS_MASKED_DETAIL_KEYS = [
        'customer_email',
        'customer_phone',
        'requester_email',
        'user_email',
    ];

    public static function customerPnrDisplay(?string $pnr): string
    {
        $trimmed = trim((string) ($pnr ?? ''));

        return $trimmed !== ''
            ? $trimmed
            : (string) EmailPlaceholderFallbacks::fallbackFor('pnr');
    }

    public static function shouldShowPnrRow(?string $pnr, bool $alwaysShow = true): bool
    {
        if ($alwaysShow) {
            return true;
        }

        return trim((string) ($pnr ?? '')) !== '';
    }

    public static function maskEmail(?string $email): string
    {
        $email = trim((string) ($email ?? ''));
        if ($email === '' || ! str_contains($email, '@')) {
            return 'Available in admin panel';
        }

        [$local, $domain] = explode('@', $email, 2);
        $local = (string) $local;
        if (strlen($local) <= 2) {
            return '***@'.$domain;
        }

        return substr($local, 0, 1).'***@'.$domain;
    }

    public static function maskPhone(?string $phone): string
    {
        $digits = preg_replace('/\D+/', '', (string) ($phone ?? '')) ?? '';
        if ($digits === '') {
            return 'Available in admin panel';
        }

        if (strlen($digits) <= 4) {
            return '***'.$digits;
        }

        return '***'.substr($digits, -4);
    }

    public static function isBlockedOpsDetailKey(string $key): bool
    {
        $normalized = strtolower($key);

        foreach (self::OPS_BLOCKED_DETAIL_KEYS as $blocked) {
            if ($normalized === $blocked || str_contains($normalized, $blocked)) {
                return true;
            }
        }

        return false;
    }

    public static function formatOpsDetailValue(string $key, string $value): string
    {
        if (in_array($key, self::OPS_MASKED_DETAIL_KEYS, true)) {
            return $key === 'customer_phone' || $key === 'phone'
                ? self::maskPhone($value)
                : self::maskEmail($value);
        }

        return $value;
    }

    /**
     * @param  array{
     *     emailMode?: string,
     *     headline?: string|null,
     *     intro?: string|null,
     *     statusBannerLabel?: string|null,
     *     statusBannerTone?: string|null,
     *     headerLabel?: string|null,
     *     actionCardTitle?: string|null,
     *     actionCardBody?: string|null,
     *     detailsTitle?: string|null,
     *     details?: list<array{label: string, value: string}>,
     *     nextSteps?: list<string>,
     *     contentHtml?: string|null,
     *     ctaUrl?: string|null,
     *     ctaLabel?: string|null,
     *     footerDisclaimer?: string|null,
     *     statusLabel?: string|null,
     * }  $options
     * @return array<string, mixed>
     */
    public static function viewData(array $options): array
    {
        $emailMode = (string) ($options['emailMode'] ?? self::MODE_CUSTOMER);
        $tone = (string) ($options['statusBannerTone'] ?? 'info');
        if (! isset(self::STATUS_TONES[$tone])) {
            $tone = 'info';
        }

        $footerDisclaimer = trim((string) ($options['footerDisclaimer'] ?? ''));
        if ($footerDisclaimer === '') {
            $footerDisclaimer = $emailMode === self::MODE_OPS
                ? 'Generated by OTA system.'
                : 'Please keep this email for your records.';
        }

        $detailsTitle = trim((string) ($options['detailsTitle'] ?? ''));
        if ($detailsTitle === '') {
            $detailsTitle = $emailMode === self::MODE_OPS ? 'Summary' : 'Booking summary';
        }

        return [
            'emailMode' => $emailMode,
            'headline' => $options['headline'] ?? null,
            'intro' => $options['intro'] ?? null,
            'statusLabel' => $options['statusLabel'] ?? null,
            'statusBannerLabel' => $options['statusBannerLabel'] ?? ($options['headline'] ?? null),
            'statusBannerTone' => $tone,
            'headerLabel' => $options['headerLabel'] ?? ($emailMode === self::MODE_OPS ? 'Operational alert' : null),
            'actionCardTitle' => $options['actionCardTitle'] ?? null,
            'actionCardBody' => $options['actionCardBody'] ?? null,
            'detailsTitle' => $detailsTitle,
            'details' => $options['details'] ?? [],
            'nextSteps' => array_values(array_filter(
                $options['nextSteps'] ?? [],
                fn (mixed $step): bool => is_string($step) && trim($step) !== '',
            )),
            'contentHtml' => $options['contentHtml'] ?? '',
            'ctaUrl' => $options['ctaUrl'] ?? null,
            'ctaLabel' => $options['ctaLabel'] ?? null,
            'footerDisclaimer' => $footerDisclaimer,
        ];
    }

    /**
     * @return array{bg: string, border: string, text: string}
     */
    public static function toneStyle(string $tone): array
    {
        return self::STATUS_TONES[$tone] ?? self::STATUS_TONES['info'];
    }
}
