<?php

namespace App\Support\Emails;

use App\Models\Agency;
use App\Models\Booking;
use App\Services\Communication\NotificationTemplateRenderer;
use App\Support\Branding\CompanyEmailProfile;
use App\Support\Branding\CompanyEmailProfileResolver;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Str;

/**
 * Live send renderer for OtaNotificationService operational emails (I6; not customer Mailables).
 */
class OtaOperationalEmailRenderer
{
    public function __construct(
        protected NotificationTemplateRenderer $templateRenderer,
    ) {}

    /**
     * @param  array<string, scalar|null>  $variables
     */
    public function render(
        Agency $agency,
        string $eventKey,
        array $variables,
        string $fallbackSubject,
        string $fallbackBody,
        ?Booking $booking = null,
    ): OtaOperationalEmailRendered {
        $rendered = $this->templateRenderer->render(
            $agency,
            $eventKey,
            'email',
            $variables,
            $fallbackSubject,
            $fallbackBody,
            $booking,
        );

        return $this->wrapPlainContent(
            $agency,
            $eventKey,
            $rendered['subject'],
            $rendered['body'],
            $variables,
            $rendered['used_template'],
            $rendered['template_enabled'],
        );
    }

    /**
     * @param  array<string, scalar|null>  $variables
     */
    public function wrapStoredBody(
        Agency $agency,
        string $eventKey,
        string $subject,
        string $plainBody,
        array $variables = [],
    ): OtaOperationalEmailRendered {
        return $this->wrapPlainContent(
            $agency,
            $eventKey,
            $subject,
            $plainBody,
            $variables,
            usedTemplate: false,
            templateEnabled: true,
        );
    }

    /**
     * @param  array<string, scalar|null>  $variables
     */
    protected function wrapPlainContent(
        Agency $agency,
        string $eventKey,
        string $subject,
        string $plainBody,
        array $variables,
        bool $usedTemplate,
        bool $templateEnabled,
    ): OtaOperationalEmailRendered {
        $profile = CompanyEmailProfileResolver::resolve($agency);
        $definition = EmailTemplateRegistry::find('ops-'.$eventKey);
        $innerBody = $plainBody;
        $headline = trim((string) ($variables['notification_title'] ?? ''));
        if ($headline === '') {
            $headline = $definition?->name ?? Str::headline(str_replace('_', ' ', $eventKey));
        }
        $statusLabel = trim((string) ($variables['booking_status'] ?? $variables['notification_status'] ?? ''));
        $intro = $this->introFromBody($innerBody);
        [$ctaUrl, $ctaLabel] = $this->resolveCta($variables);
        $actionCard = $this->resolveActionCard($variables, $innerBody, $intro);

        $html = View::make('emails.layouts.modern', array_merge(
            ['companyEmailProfile' => $profile],
            ModernEmailLayout::viewData([
                'emailMode' => ModernEmailLayout::MODE_OPS,
                'headline' => $headline,
                'intro' => $actionCard['body'] === $intro ? null : $intro,
                'statusLabel' => $statusLabel !== '' ? $statusLabel : null,
                'statusBannerLabel' => $headline,
                'statusBannerTone' => $this->resolveStatusTone($eventKey, $variables),
                'actionCardTitle' => $actionCard['title'],
                'actionCardBody' => $actionCard['body'],
                'contentHtml' => $this->bodyToSafeHtml($this->remainingBodyHtml($innerBody, $intro, $actionCard['body'])),
                'details' => $this->detailsFromVariables($variables, $definition),
                'ctaUrl' => $ctaUrl,
                'ctaLabel' => $ctaLabel,
                'footerDisclaimer' => 'Generated by OTA system.',
            ]),
        ))->render();

        return new OtaOperationalEmailRendered(
            subject: $subject,
            html: $html,
            plainBody: $innerBody,
            usedTemplate: $usedTemplate,
            templateEnabled: $templateEnabled,
            profile: $profile,
        );
    }

    /**
     * @param  array<string, scalar|null>  $variables
     * @return array{0: ?string, 1: ?string}
     */
    protected function resolveCta(array $variables): array
    {
        $adminUrl = trim((string) ($variables['admin_booking_url'] ?? ''));
        if ($adminUrl !== '') {
            return [$adminUrl, 'Open booking'];
        }

        $manageUrl = trim((string) ($variables['manage_booking_url'] ?? ''));
        if ($manageUrl !== '') {
            return [$manageUrl, 'View booking'];
        }

        return [null, null];
    }

    protected function introFromBody(string $plainBody): ?string
    {
        $lines = array_values(array_filter(
            array_map('trim', preg_split('/\R/u', $plainBody) ?: []),
            fn (string $line): bool => $line !== '' && ! str_starts_with($line, 'Dear '),
        ));

        return $lines[0] ?? null;
    }

    /**
     * @param  array<string, scalar|null>  $variables
     * @return list<array{label: string, value: string}>
     */
    protected function detailsFromVariables(array $variables, ?EmailTemplateDefinition $definition): array
    {
        $stringVariables = [];
        foreach ($variables as $key => $value) {
            if (is_scalar($value) || $value === null) {
                $stringVariables[(string) $key] = (string) $value;
            }
        }

        $candidates = [
            'booking_reference' => 'Booking reference',
            'route' => 'Route',
            'trip_type' => 'Trip type',
            'travel_date' => 'Travel date',
            'booking_status' => 'Status',
            'pnr' => 'PNR',
            'period_label' => 'Period',
            'amount' => 'Amount',
            'currency' => 'Currency',
            'customer_name' => 'Customer',
            'customer_email' => 'Email',
            'customer_phone' => 'Phone',
            'agent_name' => 'Agent',
            'passenger_name' => 'Passenger',
            'passenger_summary' => 'Passengers',
            'payment_status' => 'Payment status',
            'user_name' => 'User',
            'user_email' => 'Email',
            'account_type' => 'Account type',
            'timestamp' => 'Date and time',
            'ip' => 'IP address',
            'user_agent' => 'Device / browser',
            'portal_label' => 'Portal',
        ];

        $rows = [];
        foreach ($candidates as $key => $label) {
            if (ModernEmailLayout::isBlockedOpsDetailKey($key)) {
                continue;
            }
            $value = trim($stringVariables[$key] ?? '');
            if ($value === '') {
                continue;
            }
            if ($definition !== null
                && ! in_array($key, $definition->variables, true)
                && ! in_array($key, ['booking_reference', 'period_label'], true)) {
                continue;
            }
            if ($key === 'amount' && isset($stringVariables['currency'])) {
                $value = trim($stringVariables['currency'].' '.$value);
            }
            $value = ModernEmailLayout::formatOpsDetailValue($key, $value);
            $rows[] = ['label' => $label, 'value' => e($value)];
        }

        return $rows;
    }

    /**
     * @param  array<string, scalar|null>  $variables
     * @return array{title: string, body: string}
     */
    protected function resolveActionCard(array $variables, string $plainBody, ?string $intro): array
    {
        $actionRequired = trim((string) ($variables['action_required'] ?? $variables['review_reason'] ?? ''));
        if ($actionRequired !== '') {
            return [
                'title' => 'Action required',
                'body' => $actionRequired,
            ];
        }

        $body = $intro ?? trim($plainBody);
        if ($body === '') {
            $body = 'Review this notification in the admin panel and take the next operational step.';
        }

        return [
            'title' => 'What to do next',
            'body' => $body,
        ];
    }

    /**
     * @param  array<string, scalar|null>  $variables
     */
    protected function resolveStatusTone(string $eventKey, array $variables): string
    {
        $event = strtolower($eventKey);
        if (str_contains($event, 'failed') || str_contains($event, 'rejected') || str_contains($event, 'alert')) {
            return 'danger';
        }
        if (str_contains($event, 'manual_review') || str_contains($event, 'proof_submitted') || str_contains($event, 'needs_more')) {
            return 'warning';
        }
        if (str_contains($event, 'verified') || str_contains($event, 'approved') || str_contains($event, 'issued') || str_contains($event, 'confirmed')) {
            return 'success';
        }

        return 'info';
    }

    protected function remainingBodyHtml(string $plainBody, ?string $intro, string $actionBody): string
    {
        $lines = array_values(array_filter(
            array_map('trim', preg_split('/\R/u', $plainBody) ?: []),
            fn (string $line): bool => $line !== '' && ! str_starts_with($line, 'Dear '),
        ));

        if ($lines === []) {
            return '';
        }

        if ($intro !== null && $lines[0] === $intro) {
            array_shift($lines);
        }

        if ($actionBody !== '' && isset($lines[0]) && $lines[0] === $actionBody) {
            array_shift($lines);
        }

        return implode("\n", $lines);
    }

    protected function bodyToSafeHtml(string $text): string
    {
        $stripped = strip_tags($text);

        return nl2br($stripped, false);
    }
}

/**
 * @internal
 */
final class OtaOperationalEmailRendered
{
    public function __construct(
        public string $subject,
        public string $html,
        public string $plainBody,
        public bool $usedTemplate,
        public bool $templateEnabled,
        public CompanyEmailProfile $profile,
    ) {}
}
