import type {
  CmsBannerFamily,
  CmsPageType,
  CmsSectionDefinition,
  CmsSectionType,
  CmsSectionVariant,
  CmsThemeMode,
} from "@/types/cms";

const FUNCTIONAL_BOUNDARY =
  "Operational logic (search, booking, payments, supplier calls) is not CMS-controlled.";

export const CMS_SECTION_REGISTRY: CmsSectionDefinition[] = [
  {
    sectionType: "homepage.hero",
    label: "Homepage hero",
    frontendComponentKey: "homepage.hero",
    supportedPageTypes: ["homepage"],
    supportedVariants: ["default", "overlay"],
    supportedThemeModes: ["automatic", "day", "night", "dualAsset"],
    supportedDeviceModes: ["all", "desktop", "mobile"],
    maxPerPage: 1,
    requiredFields: ["heading", "altText"],
    optionalFields: ["eyebrow", "supportingText", "primaryCta", "secondaryCta", "overlayStrength"],
    assetRequirements: ["desktopAssetId", "mobileAssetId"],
    aspectRatioRequirements: { desktop: "16:9", mobile: "4:5" },
    validationRules: ["missing_alt_text", "missing_mobile_asset"],
    previewCapable: true,
    apiMappingNotes: "Maps to public hero banner with optional background image.",
    functionalBoundaryNotes: FUNCTIONAL_BOUNDARY,
  },
  {
    sectionType: "homepage.flightSearchContext",
    label: "Flight search context",
    frontendComponentKey: "homepage.flightSearchContext",
    supportedPageTypes: ["homepage"],
    supportedVariants: ["default"],
    supportedThemeModes: ["automatic", "day", "night"],
    supportedDeviceModes: ["all"],
    maxPerPage: 1,
    requiredFields: ["searchRelationship"],
    optionalFields: ["helperText"],
    assetRequirements: [],
    aspectRatioRequirements: {},
    validationRules: ["functional_boundary"],
    previewCapable: true,
    apiMappingNotes: "Wraps fixed flight search component; CMS controls labels only.",
    functionalBoundaryNotes: "Flight search mechanics are not CMS-controlled.",
  },
  {
    sectionType: "homepage.featuredOffers",
    label: "Featured offers",
    frontendComponentKey: "homepage.featuredOffers",
    supportedPageTypes: ["homepage", "campaign_landing"],
    supportedVariants: ["default", "grid", "carousel"],
    supportedThemeModes: ["automatic", "day", "night", "neutral"],
    supportedDeviceModes: ["all"],
    maxPerPage: 1,
    requiredFields: ["title"],
    optionalFields: ["subtitle", "displayVariant"],
    assetRequirements: ["imageAssetId"],
    aspectRatioRequirements: { desktop: "4:3", mobile: "4:3" },
    validationRules: ["too_many_offer_cards", "carousel_required"],
    previewCapable: true,
    apiMappingNotes: "Static promotional offers; not live bookable fares unless linked to search preset.",
    functionalBoundaryNotes: "Fare calculation and availability are not CMS-controlled.",
  },
  {
    sectionType: "homepage.popularRoutes",
    label: "Popular routes",
    frontendComponentKey: "homepage.popularRoutes",
    supportedPageTypes: ["homepage"],
    supportedVariants: ["default", "grid"],
    supportedThemeModes: ["automatic", "day", "night"],
    supportedDeviceModes: ["all"],
    maxPerPage: 1,
    requiredFields: ["title"],
    optionalFields: ["subtitle"],
    assetRequirements: [],
    aspectRatioRequirements: {},
    validationRules: [],
    previewCapable: true,
    apiMappingNotes: "Route cards with approved search parameter metadata.",
    functionalBoundaryNotes: "Supplier and fare logic are not CMS-controlled.",
  },
  {
    sectionType: "homepage.featuredDestinations",
    label: "Featured destinations",
    frontendComponentKey: "homepage.featuredDestinations",
    supportedPageTypes: ["homepage", "destination_landing"],
    supportedVariants: ["default", "grid", "carousel"],
    supportedThemeModes: ["automatic", "day", "night", "dualAsset"],
    supportedDeviceModes: ["all"],
    maxPerPage: 1,
    requiredFields: ["title"],
    optionalFields: ["subtitle"],
    assetRequirements: ["imageAssetId"],
    aspectRatioRequirements: { desktop: "3:2", mobile: "1:1" },
    validationRules: [],
    previewCapable: true,
    apiMappingNotes: "Destination cards with teaser copy and CTA.",
    functionalBoundaryNotes: FUNCTIONAL_BOUNDARY,
  },
  {
    sectionType: "homepage.airlineHighlights",
    label: "Airline highlights",
    frontendComponentKey: "homepage.airlineHighlights",
    supportedPageTypes: ["homepage", "airline_info"],
    supportedVariants: ["default", "grid"],
    supportedThemeModes: ["automatic", "neutral"],
    supportedDeviceModes: ["all"],
    maxPerPage: 1,
    requiredFields: ["title"],
    optionalFields: ["supportingText"],
    assetRequirements: [],
    aspectRatioRequirements: {},
    validationRules: ["approved_icon_key"],
    previewCapable: true,
    apiMappingNotes: "Approved icon identifiers only.",
    functionalBoundaryNotes: "Supplier credentials and pairing are not CMS-controlled.",
  },
  {
    sectionType: "homepage.trustBenefits",
    label: "Trust and benefits",
    frontendComponentKey: "homepage.trustBenefits",
    supportedPageTypes: ["homepage", "about"],
    supportedVariants: ["default", "grid"],
    supportedThemeModes: ["automatic", "day", "night"],
    supportedDeviceModes: ["all"],
    maxPerPage: 1,
    requiredFields: ["title"],
    optionalFields: ["subtitle"],
    assetRequirements: [],
    aspectRatioRequirements: {},
    validationRules: ["approved_icon_key"],
    previewCapable: true,
    apiMappingNotes: "Maps to why-choose-us / trust metrics sections.",
    functionalBoundaryNotes: FUNCTIONAL_BOUNDARY,
  },
  {
    sectionType: "homepage.supportCallout",
    label: "Support callout",
    frontendComponentKey: "homepage.supportCallout",
    supportedPageTypes: ["homepage", "support", "contact"],
    supportedVariants: ["banner", "default"],
    supportedThemeModes: ["automatic", "day", "night", "dualAsset"],
    supportedDeviceModes: ["all", "desktop", "mobile"],
    maxPerPage: 1,
    requiredFields: ["heading", "altText", "primaryCta"],
    optionalFields: ["supportingText", "whatsappCta"],
    assetRequirements: ["desktopAssetId", "mobileAssetId"],
    aspectRatioRequirements: { desktop: "21:9", mobile: "16:9" },
    validationRules: ["missing_alt_text", "missing_mobile_asset"],
    previewCapable: true,
    apiMappingNotes: "Wide desktop support banner with WhatsApp CTA metadata.",
    functionalBoundaryNotes: "Support ticket creation is not CMS-controlled.",
  },
  {
    sectionType: "homepage.faqPreview",
    label: "FAQ preview",
    frontendComponentKey: "homepage.faqPreview",
    supportedPageTypes: ["homepage", "faq"],
    supportedVariants: ["default", "compact"],
    supportedThemeModes: ["automatic", "neutral"],
    supportedDeviceModes: ["all"],
    maxPerPage: 1,
    requiredFields: ["title"],
    optionalFields: ["subtitle"],
    assetRequirements: [],
    aspectRatioRequirements: {},
    validationRules: ["empty_faq_answer"],
    previewCapable: true,
    apiMappingNotes: "Featured FAQ items from structured FAQ collection.",
    functionalBoundaryNotes: FUNCTIONAL_BOUNDARY,
  },
  {
    sectionType: "homepage.newsletterCallout",
    label: "Newsletter callout",
    frontendComponentKey: "homepage.newsletterCallout",
    supportedPageTypes: ["homepage"],
    supportedVariants: ["default", "compact"],
    supportedThemeModes: ["automatic", "neutral"],
    supportedDeviceModes: ["all"],
    maxPerPage: 1,
    requiredFields: ["heading"],
    optionalFields: ["supportingText", "primaryCta"],
    assetRequirements: [],
    aspectRatioRequirements: {},
    validationRules: [],
    previewCapable: true,
    apiMappingNotes: "Contact/newsletter callout without raw HTML.",
    functionalBoundaryNotes: "Email delivery is not CMS-controlled.",
  },
  {
    sectionType: "global.noticeStrip",
    label: "Notice strip",
    frontendComponentKey: "global.noticeStrip",
    supportedPageTypes: ["homepage", "about", "contact", "faq", "support"],
    supportedVariants: ["default"],
    supportedThemeModes: ["automatic", "day", "night"],
    supportedDeviceModes: ["all"],
    maxPerPage: 2,
    requiredFields: ["message", "severity"],
    optionalFields: ["title", "cta"],
    assetRequirements: [],
    aspectRatioRequirements: {},
    validationRules: ["publication_window"],
    previewCapable: true,
    apiMappingNotes: "Global alert strip above page content.",
    functionalBoundaryNotes: FUNCTIONAL_BOUNDARY,
  },
  {
    sectionType: "global.promotionBanner",
    label: "Promotion banner",
    frontendComponentKey: "global.promotionBanner",
    supportedPageTypes: ["homepage", "campaign_landing"],
    supportedVariants: ["banner", "default"],
    supportedThemeModes: ["automatic", "day", "night"],
    supportedDeviceModes: ["all"],
    maxPerPage: 3,
    requiredFields: ["heading"],
    optionalFields: ["primaryCta"],
    assetRequirements: ["desktopAssetId"],
    aspectRatioRequirements: { desktop: "3:1", mobile: "2:1" },
    validationRules: [],
    previewCapable: true,
    apiMappingNotes: "Campaign promotion banner family.",
    functionalBoundaryNotes: FUNCTIONAL_BOUNDARY,
  },
  {
    sectionType: "content.richText",
    label: "Rich text content",
    frontendComponentKey: "content.richText",
    supportedPageTypes: ["about", "travel_guidance", "umrah"],
    supportedVariants: ["default"],
    supportedThemeModes: ["automatic", "neutral"],
    supportedDeviceModes: ["all"],
    maxPerPage: null,
    requiredFields: ["heading", "body"],
    optionalFields: [],
    assetRequirements: [],
    aspectRatioRequirements: {},
    validationRules: ["no_raw_html"],
    previewCapable: true,
    apiMappingNotes: "Structured text blocks only.",
    functionalBoundaryNotes: "No arbitrary HTML execution.",
  },
  {
    sectionType: "content.policyPage",
    label: "Policy page content",
    frontendComponentKey: "content.policyPage",
    supportedPageTypes: ["privacy", "terms", "refund"],
    supportedVariants: ["default"],
    supportedThemeModes: ["neutral"],
    supportedDeviceModes: ["all"],
    maxPerPage: 1,
    requiredFields: ["heading", "body"],
    optionalFields: ["lastReviewedDate"],
    assetRequirements: [],
    aspectRatioRequirements: {},
    validationRules: ["no_raw_html"],
    previewCapable: true,
    apiMappingNotes: "Legal/policy structured content.",
    functionalBoundaryNotes: FUNCTIONAL_BOUNDARY,
  },
  {
    sectionType: "content.contactBlock",
    label: "Contact block",
    frontendComponentKey: "content.contactBlock",
    supportedPageTypes: ["contact", "support"],
    supportedVariants: ["default"],
    supportedThemeModes: ["automatic", "day", "night"],
    supportedDeviceModes: ["all"],
    maxPerPage: 1,
    requiredFields: ["heading"],
    optionalFields: ["supportingText", "primaryCta", "whatsappCta"],
    assetRequirements: [],
    aspectRatioRequirements: {},
    validationRules: [],
    previewCapable: true,
    apiMappingNotes: "Contact and support presentation block.",
    functionalBoundaryNotes: "Form submission handling is not CMS-controlled.",
  },
  {
    sectionType: "content.faqCollection",
    label: "FAQ collection",
    frontendComponentKey: "content.faqCollection",
    supportedPageTypes: ["faq", "support"],
    supportedVariants: ["default", "compact"],
    supportedThemeModes: ["neutral"],
    supportedDeviceModes: ["all"],
    maxPerPage: 1,
    requiredFields: ["title"],
    optionalFields: ["subtitle"],
    assetRequirements: [],
    aspectRatioRequirements: {},
    validationRules: ["empty_faq_answer"],
    previewCapable: true,
    apiMappingNotes: "Full FAQ listing from structured items.",
    functionalBoundaryNotes: FUNCTIONAL_BOUNDARY,
  },
  {
    sectionType: "content.destinationHero",
    label: "Destination hero",
    frontendComponentKey: "content.destinationHero",
    supportedPageTypes: ["destination_landing"],
    supportedVariants: ["default", "overlay"],
    supportedThemeModes: ["automatic", "day", "night", "dualAsset"],
    supportedDeviceModes: ["all"],
    maxPerPage: 1,
    requiredFields: ["heading", "altText"],
    optionalFields: ["eyebrow", "supportingText", "primaryCta"],
    assetRequirements: ["desktopAssetId", "mobileAssetId"],
    aspectRatioRequirements: { desktop: "16:9", mobile: "4:5" },
    validationRules: ["missing_alt_text"],
    previewCapable: true,
    apiMappingNotes: "Destination landing hero.",
    functionalBoundaryNotes: FUNCTIONAL_BOUNDARY,
  },
  {
    sectionType: "content.destinationHighlights",
    label: "Destination highlights",
    frontendComponentKey: "content.destinationHighlights",
    supportedPageTypes: ["destination_landing"],
    supportedVariants: ["default", "grid"],
    supportedThemeModes: ["automatic", "neutral"],
    supportedDeviceModes: ["all"],
    maxPerPage: 1,
    requiredFields: ["title"],
    optionalFields: ["subtitle"],
    assetRequirements: ["imageAssetId"],
    aspectRatioRequirements: { desktop: "3:2", mobile: "1:1" },
    validationRules: [],
    previewCapable: true,
    apiMappingNotes: "Destination highlight cards.",
    functionalBoundaryNotes: FUNCTIONAL_BOUNDARY,
  },
];

export function getSectionDefinition(sectionType: CmsSectionType): CmsSectionDefinition | undefined {
  return CMS_SECTION_REGISTRY.find((d) => d.sectionType === sectionType);
}

export function getRegistryKeys(): string[] {
  return CMS_SECTION_REGISTRY.map((d) => d.frontendComponentKey);
}

export function isThemeModeSupported(sectionType: CmsSectionType, themeMode: CmsThemeMode): boolean {
  const def = getSectionDefinition(sectionType);
  return def ? def.supportedThemeModes.includes(themeMode) : false;
}

export function isPageTypeAllowed(sectionType: CmsSectionType, pageType: CmsPageType): boolean {
  const def = getSectionDefinition(sectionType);
  return def ? def.supportedPageTypes.includes(pageType) : false;
}

export const CMS_BANNER_FAMILY_RULES: Record<
  CmsBannerFamily,
  {
    placements: string[];
    desktopAspectRatio: string;
    mobileAspectRatio: string;
    supportsDayNight: boolean;
    requiresAltText: boolean;
    overlayAllowed: boolean;
    textAllowed: boolean;
    ctaAllowed: boolean;
  }
> = {
  hero: {
    placements: ["homepage_top"],
    desktopAspectRatio: "16:9",
    mobileAspectRatio: "4:5",
    supportsDayNight: true,
    requiresAltText: true,
    overlayAllowed: true,
    textAllowed: true,
    ctaAllowed: true,
  },
  support: {
    placements: ["homepage_mid", "support_page"],
    desktopAspectRatio: "21:9",
    mobileAspectRatio: "16:9",
    supportsDayNight: true,
    requiresAltText: true,
    overlayAllowed: true,
    textAllowed: true,
    ctaAllowed: true,
  },
  offer: {
    placements: ["homepage_fares", "campaign"],
    desktopAspectRatio: "4:3",
    mobileAspectRatio: "4:3",
    supportsDayNight: false,
    requiresAltText: true,
    overlayAllowed: false,
    textAllowed: true,
    ctaAllowed: true,
  },
  destination: {
    placements: ["homepage_destinations", "destination_landing"],
    desktopAspectRatio: "3:2",
    mobileAspectRatio: "1:1",
    supportsDayNight: true,
    requiresAltText: true,
    overlayAllowed: true,
    textAllowed: true,
    ctaAllowed: true,
  },
  airline: {
    placements: ["homepage_airlines"],
    desktopAspectRatio: "1:1",
    mobileAspectRatio: "1:1",
    supportsDayNight: false,
    requiresAltText: true,
    overlayAllowed: false,
    textAllowed: true,
    ctaAllowed: false,
  },
  campaign: {
    placements: ["campaign_landing"],
    desktopAspectRatio: "3:1",
    mobileAspectRatio: "2:1",
    supportsDayNight: true,
    requiresAltText: true,
    overlayAllowed: true,
    textAllowed: true,
    ctaAllowed: true,
  },
  promotion: {
    placements: ["global_strip", "homepage"],
    desktopAspectRatio: "3:1",
    mobileAspectRatio: "2:1",
    supportsDayNight: false,
    requiresAltText: true,
    overlayAllowed: false,
    textAllowed: true,
    ctaAllowed: true,
  },
  notice: {
    placements: ["global_strip"],
    desktopAspectRatio: "auto",
    mobileAspectRatio: "auto",
    supportsDayNight: false,
    requiresAltText: false,
    overlayAllowed: false,
    textAllowed: true,
    ctaAllowed: true,
  },
};

export const CMS_PREVIEW_MODES = [
  { mode: "desktop_day" as const, viewportWidth: 1280, themeMode: "day" as CmsThemeMode, label: "Desktop day" },
  { mode: "desktop_night" as const, viewportWidth: 1280, themeMode: "night" as CmsThemeMode, label: "Desktop night" },
  { mode: "tablet" as const, viewportWidth: 768, themeMode: "automatic" as CmsThemeMode, label: "Tablet" },
  { mode: "mobile_day" as const, viewportWidth: 390, themeMode: "day" as CmsThemeMode, label: "Mobile day" },
  { mode: "mobile_night" as const, viewportWidth: 390, themeMode: "night" as CmsThemeMode, label: "Mobile night" },
] as const;

export const OFFER_CAROUSEL_THRESHOLD = 3;

export function requiresOfferCarousel(offerCount: number): boolean {
  return offerCount > OFFER_CAROUSEL_THRESHOLD;
}

export function getSupportedVariants(sectionType: CmsSectionType): CmsSectionVariant[] {
  return getSectionDefinition(sectionType)?.supportedVariants ?? [];
}
