<?php

namespace App\Services\Ai;

use App\Contracts\Ai\InferenceProvider;
use App\Models\AiConversation;
use App\Models\AiMessage;
use Illuminate\Support\Facades\File;

/**
 * LLM-assisted conversational layer with approved tool dispatch.
 * Falls back to null when provider unavailable — caller uses structured pipeline.
 */
final class AiConversationalAgent
{
    public function __construct(
        private readonly InferenceProvider $provider,
        private readonly AiAssistantToolExecutor $tools,
    ) {}

    public function isEnabled(): bool
    {
        if (! (bool) config('ota.ai_assistant.conversational_enabled', true)) {
            return false;
        }

        return $this->provider->isHealthy();
    }

    /**
     * @param  array<string, mixed>  $meta
     * @return array<string, mixed>|null
     */
    public function tryHandle(AiConversation $conversation, string $message, array $meta): ?array
    {
        if (! $this->isEnabled()) {
            return null;
        }

        $history = $this->buildHistory($conversation);
        $payload = json_encode([
            'message' => $message,
            'history' => $history,
            'state' => $conversation->shopping_state,
        ], JSON_UNESCAPED_UNICODE);

        $result = $this->provider->complete([
            ['role' => 'system', 'content' => $this->systemPrompt()],
            ['role' => 'user', 'content' => (string) $payload],
        ], 420);

        if (! ($result['ok'] ?? false)) {
            return null;
        }

        $parsed = $this->decodeJsonObject((string) ($result['content'] ?? ''));
        if ($parsed === null) {
            return null;
        }

        $action = strtolower((string) ($parsed['action'] ?? 'respond'));
        if ($action === 'tool') {
            $tool = strtolower((string) ($parsed['tool'] ?? ''));
            if ($tool === 'human_handoff') {
                return ['handoff' => true, 'mode' => 'LLM_ASSISTED'];
            }

            $toolResult = $this->tools->execute($tool, is_array($parsed['args'] ?? null) ? $parsed['args'] : [], $conversation, $message);

            return [
                'mode' => 'LLM_ASSISTED',
                'tool' => $tool,
                'tool_result' => $toolResult,
                'message' => (string) ($toolResult['message'] ?? ''),
                'recommendations' => $toolResult['recommendations'] ?? [],
                'knowledge' => $toolResult['knowledge'] ?? [],
                'actions' => $toolResult['actions'] ?? [],
                'meta' => array_merge($meta, ['llm_tool' => $tool]),
            ];
        }

        $reply = trim((string) ($parsed['message'] ?? ''));
        if ($reply === '') {
            return null;
        }

        return [
            'mode' => 'LLM_ASSISTED',
            'message' => $reply,
            'meta' => $meta,
        ];
    }

    /**
     * Open-domain / casual reply generated by the model (not deterministic templates).
     *
     * @param  list<string>  $capabilities
     * @param  array<string, mixed>  $meta
     * @return array<string, mixed>|null
     */
    public function tryOpenDomainRespond(
        AiConversation $conversation,
        string $message,
        string $category,
        string $brand,
        array $capabilities,
        array $meta = [],
    ): ?array {
        if (! $this->isEnabled()) {
            return null;
        }

        $payload = [
            'task' => 'open_domain_respond',
            'category' => $category,
            'brand_name' => $brand,
            'assistant_identity' => $brand.' AI travel assistant',
            'enabled_capabilities' => array_values($capabilities),
            'message' => $message,
            'history' => $this->buildHistory($conversation),
            'policy' => [
                'brief' => true,
                'redirect_only_to_enabled_capabilities' => true,
                'never_mention_other_brands' => true,
                'no_live_unverified_facts' => $category === 'CURRENT_UNVERIFIED',
            ],
        ];

        $result = $this->provider->complete([
            ['role' => 'system', 'content' => $this->openDomainSystemPrompt()],
            ['role' => 'user', 'content' => (string) json_encode($payload, JSON_UNESCAPED_UNICODE)],
        ], 280);

        if (! ($result['ok'] ?? false)) {
            return null;
        }

        $reply = $this->extractMessage((string) ($result['content'] ?? ''));
        if ($reply === null || $reply === '') {
            return null;
        }

        if ($category === 'CURRENT_UNVERIFIED' && $this->looksLikeFabricatedLiveFact($reply)) {
            return null;
        }

        if (strcasecmp($brand, 'JetPakistan') !== 0
            && preg_match('/\bjetpakistan\b/ui', $reply) === 1) {
            return null;
        }

        return [
            'mode' => 'LLM_ASSISTED',
            'message' => $reply,
            'meta' => array_merge($meta, [
                'open_domain_category' => $category,
                'LLM_SYNTHESIS' => 'YES',
                'ANSWER_GROUNDED' => $category === 'GENERAL_KNOWLEDGE' ? 'MODEL_GENERAL' : 'N/A',
                'SMART_REDIRECT' => $capabilities !== [] ? 'YES' : 'NO',
            ]),
        ];
    }

    /**
     * Synthesize a natural answer strictly from approved knowledge excerpts.
     *
     * @param  list<array{slug: string, title: string, excerpt: string, score?: float}>  $hits
     * @param  array<string, mixed>  $meta
     * @return array<string, mixed>|null
     */
    public function tryGroundedKnowledgeRespond(
        AiConversation $conversation,
        string $message,
        array $hits,
        string $brand,
        array $meta = [],
    ): ?array {
        if (! $this->isEnabled() || $hits === []) {
            return null;
        }

        $sources = [];
        foreach ($hits as $hit) {
            $sources[] = [
                'slug' => (string) ($hit['slug'] ?? ''),
                'title' => (string) ($hit['title'] ?? ''),
                'excerpt' => (string) ($hit['excerpt'] ?? ''),
            ];
        }

        $payload = [
            'task' => 'grounded_knowledge_respond',
            'brand_name' => $brand,
            'message' => $message,
            'approved_sources' => $sources,
            'history' => $this->buildHistory($conversation),
            'policy' => [
                'use_only_approved_sources' => true,
                'do_not_invent_company_facts' => true,
                'brief' => true,
            ],
        ];

        $result = $this->provider->complete([
            ['role' => 'system', 'content' => $this->openDomainSystemPrompt()],
            ['role' => 'user', 'content' => (string) json_encode($payload, JSON_UNESCAPED_UNICODE)],
        ], 320);

        if (! ($result['ok'] ?? false)) {
            return null;
        }

        $reply = $this->extractMessage((string) ($result['content'] ?? ''));
        if ($reply === null || $reply === '') {
            return null;
        }

        return [
            'mode' => 'LLM_ASSISTED',
            'message' => $reply,
            'meta' => array_merge($meta, [
                'LLM_SYNTHESIS' => 'YES',
                'ANSWER_GROUNDED' => 'YES',
            ]),
        ];
    }

    /**
     * @return list<array{role: string, content: string}>
     */
    private function buildHistory(AiConversation $conversation): array
    {
        return $conversation->messages()
            ->orderByDesc('id')
            ->limit(12)
            ->get()
            ->reverse()
            ->map(static fn (AiMessage $m): array => [
                'role' => $m->role === 'assistant' ? 'assistant' : 'user',
                'content' => $m->body,
            ])
            ->values()
            ->all();
    }

    private function systemPrompt(): string
    {
        $path = base_path('ai-assistant/prompts/assistant-conversational-system.txt');
        if (File::isFile($path)) {
            return trim((string) File::get($path));
        }

        return 'Return JSON only for Ask JetPakistan assistant actions.';
    }

    private function openDomainSystemPrompt(): string
    {
        $path = base_path('ai-assistant/prompts/assistant-open-domain-system.txt');
        if (File::isFile($path)) {
            return trim((string) File::get($path));
        }

        return 'Return JSON only: {"message":"..."}';
    }

    private function extractMessage(string $content): ?string
    {
        $parsed = $this->decodeJsonObject($content);
        if (is_array($parsed)) {
            $reply = trim((string) ($parsed['message'] ?? ''));

            return $reply !== '' ? $reply : null;
        }

        $trimmed = trim($content);
        if ($trimmed === '' || str_starts_with($trimmed, '{')) {
            return null;
        }

        return $trimmed;
    }

    private function looksLikeFabricatedLiveFact(string $reply): bool
    {
        $lower = mb_strtolower($reply);
        if (preg_match('/\$\s?\d|\b\d{2,}\s*(usd|pkr|points|degrees)\b/u', $lower) === 1) {
            return true;
        }
        if (preg_match('/\b(currently|right now|as of today)\b.*\b\d/u', $lower) === 1) {
            return true;
        }

        return false;
    }

    /**
     * @return array<string, mixed>|null
     */
    private function decodeJsonObject(string $content): ?array
    {
        $content = trim($content);
        if ($content === '') {
            return null;
        }

        if (preg_match('/\{[\s\S]*\}/', $content, $m) === 1) {
            $content = $m[0];
        }

        try {
            $decoded = json_decode($content, true, 32, JSON_THROW_ON_ERROR);
        } catch (\Throwable) {
            return null;
        }

        return is_array($decoded) ? $decoded : null;
    }
}
