<?php

namespace App\Services\Ai;

use App\Contracts\Ai\InferenceProvider;
use App\Models\AiConversation;
use App\Models\AiMessage;
use Illuminate\Support\Facades\File;

/**
 * LLM-assisted conversational layer with approved tool dispatch.
 * Falls back to null when provider unavailable — caller uses structured pipeline.
 */
final class AiConversationalAgent
{
    public function __construct(
        private readonly InferenceProvider $provider,
        private readonly AiAssistantToolExecutor $tools,
    ) {}

    public function isEnabled(): bool
    {
        if (! (bool) config('ota.ai_assistant.conversational_enabled', true)) {
            return false;
        }

        return $this->provider->isHealthy();
    }

    /**
     * @param  array<string, mixed>  $meta
     * @return array<string, mixed>|null
     */
    public function tryHandle(AiConversation $conversation, string $message, array $meta): ?array
    {
        if (! $this->isEnabled()) {
            return null;
        }

        $history = $this->buildHistory($conversation);
        $payload = json_encode([
            'message' => $message,
            'history' => $history,
            'state' => $conversation->shopping_state,
        ], JSON_UNESCAPED_UNICODE);

        $result = $this->provider->complete([
            ['role' => 'system', 'content' => $this->systemPrompt()],
            ['role' => 'user', 'content' => (string) $payload],
        ], 420);

        if (! ($result['ok'] ?? false)) {
            return null;
        }

        $parsed = $this->decodeJsonObject((string) ($result['content'] ?? ''));
        if ($parsed === null) {
            return null;
        }

        $action = strtolower((string) ($parsed['action'] ?? 'respond'));
        if ($action === 'tool') {
            $tool = strtolower((string) ($parsed['tool'] ?? ''));
            if ($tool === 'human_handoff') {
                return ['handoff' => true, 'mode' => 'LLM_ASSISTED'];
            }

            $toolResult = $this->tools->execute($tool, is_array($parsed['args'] ?? null) ? $parsed['args'] : [], $conversation, $message);
            $toolMeta = is_array($toolResult['meta'] ?? null) ? $toolResult['meta'] : [];

            return [
                'mode' => 'LLM_ASSISTED',
                'tool' => $tool,
                'tool_result' => $toolResult,
                'status' => (string) ($toolResult['status'] ?? 'ok'),
                'requires_confirmation' => (bool) ($toolResult['requires_confirmation'] ?? false),
                'confirmation_snapshot' => $toolResult['confirmation_snapshot'] ?? null,
                'message' => (string) ($toolResult['message'] ?? ''),
                'recommendations' => $toolResult['recommendations'] ?? [],
                'knowledge' => $toolResult['knowledge'] ?? [],
                'actions' => $toolResult['actions'] ?? [],
                'meta' => array_merge($meta, $toolMeta, ['llm_tool' => $tool]),
            ];
        }

        $reply = trim((string) ($parsed['message'] ?? ''));
        if ($reply === '') {
            return null;
        }

        return [
            'mode' => 'LLM_ASSISTED',
            'message' => $reply,
            'meta' => $meta,
        ];
    }

    /**
     * Open-domain / casual reply generated by the model (not deterministic templates).
     *
     * @param  list<string>  $capabilities
     * @param  array<string, mixed>  $meta
     * @return array<string, mixed>|null
     */
    public function tryOpenDomainRespond(
        AiConversation $conversation,
        string $message,
        string $category,
        string $brand,
        array $capabilities,
        array $meta = [],
    ): ?array {
        if (! $this->isEnabled()) {
            return null;
        }

        $plainTextCategory = in_array($category, [
            'GENERAL_KNOWLEDGE',
            'CASUAL_CONVERSATION',
            'OUT_OF_DOMAIN_SAFE',
        ], true);

        $payload = [
            'task' => 'open_domain_respond',
            'category' => $category,
            'brand_name' => $brand,
            'assistant_identity' => $category === 'GENERAL_KNOWLEDGE' || $category === 'CASUAL_CONVERSATION'
                ? $brand.' AI assistant'
                : $brand.' AI travel assistant',
            'enabled_capabilities' => array_values($capabilities),
            'message' => $message,
            'history' => $this->buildHistory($conversation),
            'policy' => [
                'brief' => true,
                'redirect_only_to_enabled_capabilities' => true,
                'never_mention_other_brands' => true,
                'answer_stable_general_knowledge' => $category === 'GENERAL_KNOWLEDGE',
                'capabilities_do_not_forbid_general_knowledge' => true,
                'never_refuse_solely_because_non_travel' => $category === 'GENERAL_KNOWLEDGE',
                'no_live_unverified_facts' => $category === 'CURRENT_UNVERIFIED',
                'current_unverified_message_must_be_limitation_only' => $category === 'CURRENT_UNVERIFIED',
                'response_format' => $plainTextCategory ? 'plain_text' : 'json',
                'prefer_schema' => $category === 'CURRENT_UNVERIFIED'
                    ? ['message' => 'string', 'can_verify_live' => false]
                    : ($plainTextCategory ? null : ['message' => 'string']),
            ],
        ];

        $result = $this->provider->complete([
            ['role' => 'system', 'content' => $this->openDomainSystemPrompt()],
            ['role' => 'user', 'content' => (string) json_encode($payload, JSON_UNESCAPED_UNICODE)],
        ], 280);

        $latency = max(0, (int) ($result['latency_ms'] ?? 0));
        $attemptMeta = [
            'OPEN_DOMAIN_LATENCY_MS' => $latency,
            'open_domain_category' => $category,
            'OPEN_DOMAIN_ATTEMPTED' => 'YES',
            'OPEN_DOMAIN_RESPONSE_FORMAT' => $plainTextCategory ? 'plain_text' : 'json',
        ];

        if (! ($result['ok'] ?? false)) {
            return [
                'mode' => null,
                'message' => '',
                'latency_ms' => $latency,
                'calls' => 1,
                'meta' => array_merge($meta, $attemptMeta, [
                    'OPEN_DOMAIN_FALLBACK' => 'YES',
                    'OPEN_DOMAIN_REJECT_REASON' => ($result['error'] ?? null) ? 'provider_error' : 'provider_unhealthy',
                    'LLM_SYNTHESIS' => 'FALLBACK_STRUCTURED',
                ]),
            ];
        }

        $content = (string) ($result['content'] ?? '');
        if (trim($content) === '') {
            return [
                'mode' => null,
                'message' => '',
                'latency_ms' => $latency,
                'calls' => 1,
                'meta' => array_merge($meta, $attemptMeta, [
                    'OPEN_DOMAIN_FALLBACK' => 'YES',
                    'OPEN_DOMAIN_REJECT_REASON' => 'empty_output',
                    'LLM_SYNTHESIS' => 'FALLBACK_STRUCTURED',
                ]),
            ];
        }

        $parsed = null;
        $jsonValid = false;
        if ($plainTextCategory) {
            $reply = (string) ($this->extractPlainTextAnswer($content) ?? '');
        } else {
            $parsed = $this->decodeJsonObject($content);
            $jsonValid = is_array($parsed);
            $reply = $jsonValid
                ? trim((string) ($parsed['message'] ?? ''))
                : (string) ($this->extractMessage($content) ?? '');
        }

        if ($reply === '') {
            $rejectReason = $plainTextCategory
                ? 'empty_message'
                : ($jsonValid ? 'empty_message' : 'invalid_json');
            $rejectMeta = [
                'OPEN_DOMAIN_FALLBACK' => 'YES',
                'OPEN_DOMAIN_REJECT_REASON' => $rejectReason,
                'LLM_SYNTHESIS' => 'FALLBACK_STRUCTURED',
            ];
            if (! $plainTextCategory && ! $jsonValid) {
                $rejectMeta = array_merge($rejectMeta, $this->sanitizedOpenDomainDiagnostics($content, $result));
            }

            // CQ42-R3: one bounded GENERAL_KNOWLEDGE retry on empty_message only.
            if ($category === 'GENERAL_KNOWLEDGE' && $rejectReason === 'empty_message') {
                $retryPayload = $payload;
                $retryPayload['policy']['retry_plain_text_only'] = true;
                $retryPayload['instruction'] = 'Reply in plain text only. Write 1–3 concise sentences. No JSON. No tool or action payload.';
                $retryResult = $this->provider->complete([
                    ['role' => 'system', 'content' => $this->openDomainSystemPrompt()],
                    ['role' => 'user', 'content' => (string) json_encode($retryPayload, JSON_UNESCAPED_UNICODE)],
                ], 280);
                $retryLatency = max(0, (int) ($retryResult['latency_ms'] ?? 0));
                $retryMeta = [
                    'OPEN_DOMAIN_RETRY' => 'YES',
                    'OPEN_DOMAIN_RETRY_REASON' => 'empty_message',
                    'OPEN_DOMAIN_FIRST_ATTEMPT_LATENCY_MS' => $latency,
                    'OPEN_DOMAIN_RETRY_LATENCY_MS' => $retryLatency,
                    'OPEN_DOMAIN_LATENCY_MS' => $latency + $retryLatency,
                    'GENERAL_MODEL_CALLS' => 2,
                ];
                if (($retryResult['ok'] ?? false) && trim((string) ($retryResult['content'] ?? '')) !== '') {
                    $retryContent = (string) $retryResult['content'];
                    $retryReply = (string) ($this->extractPlainTextAnswer($retryContent) ?? '');
                    if ($retryReply !== '' && ! $this->looksLikeToolOrActionPayload($retryReply) && ! $this->isTravelOnlyRefusal($retryReply)) {
                        return [
                            'mode' => 'LLM_ASSISTED',
                            'message' => $retryReply,
                            'latency_ms' => $latency + $retryLatency,
                            'calls' => 2,
                            'meta' => array_merge($meta, $attemptMeta, $retryMeta, [
                                'OPEN_DOMAIN_FALLBACK' => 'NO',
                                'OPEN_DOMAIN_REJECT_REASON' => 'accepted',
                                'FINAL_RESPONSE_SOURCE' => 'QWEN_OPEN_DOMAIN',
                                'LLM_SYNTHESIS' => 'MODEL',
                            ]),
                        ];
                    }
                }

                return [
                    'mode' => null,
                    'message' => '',
                    'latency_ms' => $latency + $retryLatency,
                    'calls' => 2,
                    'meta' => array_merge($meta, $attemptMeta, $rejectMeta, $retryMeta),
                ];
            }

            return [
                'mode' => null,
                'message' => '',
                'latency_ms' => $latency,
                'calls' => 1,
                'meta' => array_merge($meta, $attemptMeta, $rejectMeta, [
                    'GENERAL_MODEL_CALLS' => 1,
                ]),
            ];
        }

        if ($this->looksLikeToolOrActionPayload($reply)) {
            return [
                'mode' => null,
                'message' => '',
                'latency_ms' => $latency,
                'calls' => 1,
                'meta' => array_merge($meta, $attemptMeta, [
                    'OPEN_DOMAIN_FALLBACK' => 'YES',
                    'OPEN_DOMAIN_REJECT_REASON' => 'tool_action_payload_rejected',
                    'LLM_SYNTHESIS' => 'FALLBACK_STRUCTURED',
                ]),
            ];
        }

        if ($category === 'CURRENT_UNVERIFIED') {
            if (is_array($parsed) && array_key_exists('can_verify_live', $parsed) && $parsed['can_verify_live'] !== false) {
                return [
                    'mode' => null,
                    'message' => '',
                    'latency_ms' => $latency,
                    'calls' => 1,
                    'meta' => array_merge($meta, $attemptMeta, [
                        'OPEN_DOMAIN_FALLBACK' => 'YES',
                        'OPEN_DOMAIN_REJECT_REASON' => 'can_verify_live_invalid',
                        'LLM_SYNTHESIS' => 'FALLBACK_STRUCTURED',
                    ]),
                ];
            }
            if (! $this->isAcceptableCurrentUnverifiedReply($reply)) {
                return [
                    'mode' => null,
                    'message' => '',
                    'latency_ms' => $latency,
                    'calls' => 1,
                    'meta' => array_merge($meta, $attemptMeta, [
                        'OPEN_DOMAIN_FALLBACK' => 'YES',
                        'OPEN_DOMAIN_REJECT_REASON' => 'live_fact_rejected',
                        'LLM_SYNTHESIS' => 'FALLBACK_STRUCTURED',
                        'HALLUCINATED_LIVE_FACT' => 'NO',
                    ]),
                ];
            }
        }

        if ($category === 'GENERAL_KNOWLEDGE' && $this->isTravelOnlyRefusal($reply)) {
            return [
                'mode' => null,
                'message' => '',
                'latency_ms' => $latency,
                'calls' => 1,
                'meta' => array_merge($meta, $attemptMeta, [
                    'OPEN_DOMAIN_FALLBACK' => 'YES',
                    'OPEN_DOMAIN_REJECT_REASON' => 'travel_refusal',
                    'LLM_SYNTHESIS' => 'FALLBACK_STRUCTURED',
                ]),
            ];
        }

        if (strcasecmp($brand, 'JetPakistan') !== 0
            && preg_match('/\bjetpakistan\b/ui', $reply) === 1) {
            return [
                'mode' => null,
                'message' => '',
                'latency_ms' => $latency,
                'calls' => 1,
                'meta' => array_merge($meta, $attemptMeta, [
                    'OPEN_DOMAIN_FALLBACK' => 'YES',
                    'OPEN_DOMAIN_REJECT_REASON' => 'brand_leak_rejected',
                    'LLM_SYNTHESIS' => 'FALLBACK_STRUCTURED',
                ]),
            ];
        }

        return [
            'mode' => 'LLM_ASSISTED',
            'message' => $reply,
            'latency_ms' => $latency,
            'calls' => 1,
            'meta' => array_merge($meta, $attemptMeta, [
                'LLM_SYNTHESIS' => 'YES',
                'OPEN_DOMAIN_FALLBACK' => 'NO',
                'OPEN_DOMAIN_REJECT_REASON' => 'accepted',
                'OPEN_DOMAIN_ACCEPTED' => 'YES',
                'ANSWER_GROUNDED' => $category === 'GENERAL_KNOWLEDGE' ? 'MODEL_GENERAL' : 'N/A',
                'SMART_REDIRECT' => $capabilities !== [] ? 'YES' : 'NO',
                'GENERAL_MODEL_CALLS' => 1,
            ]),
        ];
    }

    /**
     * Synthesize a natural answer strictly from approved knowledge excerpts.
     *
     * @param  list<array{slug: string, title: string, excerpt: string, score?: float}>  $hits
     * @param  array<string, mixed>  $meta
     * @return array<string, mixed>|null
     */
    public function tryGroundedKnowledgeRespond(
        AiConversation $conversation,
        string $message,
        array $hits,
        string $brand,
        array $meta = [],
    ): ?array {
        if (! $this->isEnabled() || $hits === []) {
            return null;
        }

        $sources = [];
        foreach ($hits as $hit) {
            $sources[] = [
                'slug' => (string) ($hit['slug'] ?? ''),
                'title' => (string) ($hit['title'] ?? ''),
                'excerpt' => (string) ($hit['excerpt'] ?? ''),
            ];
        }

        $payload = [
            'task' => 'grounded_knowledge_respond',
            'brand_name' => $brand,
            'message' => $message,
            'approved_sources' => $sources,
            'history' => $this->buildHistory($conversation),
            'policy' => [
                'use_only_approved_sources' => true,
                'do_not_invent_company_facts' => true,
                'brief' => true,
            ],
        ];

        $result = $this->provider->complete([
            ['role' => 'system', 'content' => $this->openDomainSystemPrompt()],
            ['role' => 'user', 'content' => (string) json_encode($payload, JSON_UNESCAPED_UNICODE)],
        ], 320);

        if (! ($result['ok'] ?? false)) {
            return null;
        }

        $reply = $this->extractMessage((string) ($result['content'] ?? ''));
        if ($reply === null || $reply === '') {
            return null;
        }

        if (! $this->isAcceptableGroundedKnowledgeReply($reply, $sources)) {
            return null;
        }

        return [
            'mode' => 'LLM_ASSISTED',
            'message' => $reply,
            'meta' => array_merge($meta, [
                'LLM_SYNTHESIS' => 'YES',
                'ANSWER_GROUNDED' => 'YES',
            ]),
        ];
    }

    /**
     * Fail-closed grounding: paraphrases OK; unsupported company facts rejected.
     *
     * @param  list<array{slug?: string, title?: string, excerpt?: string}>  $sources
     */
    private function isAcceptableGroundedKnowledgeReply(string $reply, array $sources): bool
    {
        $parts = [];
        foreach ($sources as $source) {
            $parts[] = trim((string) ($source['title'] ?? ''));
            $parts[] = trim((string) ($source['excerpt'] ?? ''));
        }
        $corpus = mb_strtolower(trim(implode("\n", array_filter($parts, static fn ($p) => $p !== ''))));
        if ($corpus === '') {
            return false;
        }

        $lower = mb_strtolower(trim($reply));
        if ($lower === '') {
            return false;
        }

        // Policy / commercial / hyperbolic claim families — must also appear in approved source text.
        $gatedPatterns = [
            '/\brefunds?\b/u',
            '/\bguarantees?\b/u',
            '/\bguaranteed\b/u',
            '/\bwarranty\b/u',
            '/\bsla\b/u',
            '/\b(fees?|surcharges?|penalties?)\b/u',
            '/\bcomplimentary\b/u',
            '/\bfree cancellation\b/u',
            '/\binsured\b/u',
            '/\b\d+\s*%\b/u',
            '/\bwithin\s+\d+\s*(minutes?|hours?|days?|weeks?|months?)\b/u',
            '/\bin\s+\d+\s*(minutes?|hours?|days?)\b/u',
            '/\baward[- ]?winning\b/u',
            '/\bgovernment[- ]?approved\b/u',
            '/\blargest\b/u',
            '/\bcheapest\b/u',
        ];

        foreach ($gatedPatterns as $pattern) {
            if (preg_match($pattern, $lower) === 1 && preg_match($pattern, $corpus) !== 1) {
                return false;
            }
        }

        // Clause-level: JetPakistan-specific factual claims need source support.
        $sentences = preg_split('/(?<=[.!?])\s+/u', $reply) ?: [$reply];
        foreach ($sentences as $sentence) {
            $clause = mb_strtolower(trim((string) $sentence));
            if ($clause === '' || $this->isGroundingConversationalGlue($clause)) {
                continue;
            }
            if (! $this->isCompanySpecificFactualClause($clause)) {
                continue;
            }
            if (! $this->clauseSupportedByApprovedCorpus($clause, $corpus)) {
                return false;
            }
        }

        return true;
    }

    private function isGroundingConversationalGlue(string $clauseLower): bool
    {
        // Pure glue without company facts may be ignored.
        if (preg_match('/\bjetpakistan\b/u', $clauseLower) === 1) {
            return false;
        }

        return preg_match(
            '/^(sure|okay|ok|thanks|thank you|here\'?s( the)?( short)?( version)?|i can help( with that)?|let me know|of course)[.!]?$/u',
            $clauseLower
        ) === 1;
    }

    private function isCompanySpecificFactualClause(string $clauseLower): bool
    {
        if (preg_match('/\bjetpakistan\b/u', $clauseLower) === 1) {
            return true;
        }

        // First-person service/product assertions in a grounded JP knowledge turn.
        return preg_match(
            '/\b(we|our)\s+(offer|offers|provide|provides|operate|operates|issue|issues|own|owns|have|has|include|includes)\b/u',
            $clauseLower
        ) === 1;
    }

    private function clauseSupportedByApprovedCorpus(string $clauseLower, string $corpusLower): bool
    {
        // Named services/products not in corpus → immediate reject.
        $serviceNouns = [
            'hotel', 'hotels', 'lounge', 'lounges', 'visa', 'visas',
            'fleet', 'aircraft', 'airline', 'airlines', 'cruise', 'cruises',
            'rail', 'bus', 'rental', 'insurance', 'car hire',
        ];
        foreach ($serviceNouns as $noun) {
            if (preg_match('/\b'.preg_quote($noun, '/').'\b/u', $clauseLower) === 1
                && preg_match('/\b'.preg_quote($noun, '/').'\b/u', $corpusLower) !== 1) {
                return false;
            }
        }

        // Numeric facts in company clauses must appear in corpus.
        if (preg_match_all('/\b\d+(?:\.\d+)?\b/u', $clauseLower, $nums) > 0) {
            foreach ($nums[0] as $num) {
                if (! str_contains($corpusLower, $num)) {
                    return false;
                }
            }
        }

        $stop = [
            'that', 'this', 'with', 'from', 'have', 'helps', 'helping', 'customers', 'customer',
            'online', 'also', 'offers', 'offer', 'provides', 'provide',
            'their', 'them', 'than', 'then', 'into', 'about', 'which', 'while', 'where', 'when',
            'your', 'ours', 'does', 'doesn', 'just', 'only', 'more', 'most', 'such', 'ready',
            'continue', 'general', 'questions', 'compare', 'options', 'available',
            'jetpakistan',
        ];

        $tokens = preg_split('/[^a-z0-9]+/u', $clauseLower, -1, PREG_SPLIT_NO_EMPTY) ?: [];
        $content = [];
        foreach ($tokens as $token) {
            if (mb_strlen($token) < 4) {
                continue;
            }
            if (in_array($token, $stop, true)) {
                continue;
            }
            $content[] = $token;
        }

        if ($content === []) {
            // Company claim with no sourceable content nouns — fail closed.
            return false;
        }

        // Every material content token must be supported (aggregate overlap is insufficient).
        foreach ($content as $token) {
            if (! $this->groundingTokenSupportedByCorpus($token, $corpusLower)) {
                return false;
            }
        }

        return true;
    }

    private function groundingTokenSupportedByCorpus(string $token, string $corpusLower): bool
    {
        if (str_contains($corpusLower, $token)) {
            return true;
        }

        foreach ($this->groundingParaphraseAliases($token) as $alias) {
            if (str_contains($corpusLower, $alias)) {
                return true;
            }
        }

        return false;
    }

    /**
     * Small safe paraphrase map only — not a soft similarity threshold.
     *
     * @return list<string>
     */
    private function groundingParaphraseAliases(string $token): array
    {
        $map = [
            'receive' => ['get'],
            'get' => ['receive'],
            'assistance' => ['help', 'support'],
            'help' => ['assistance', 'support'],
            'agency' => ['platform'],
            'platform' => ['agency'],
        ];

        return $map[$token] ?? [];
    }

    /**
     * @return list<array{role: string, content: string}>
     */
    private function buildHistory(AiConversation $conversation): array
    {
        return $conversation->messages()
            ->orderByDesc('id')
            ->limit(12)
            ->get()
            ->reverse()
            ->map(static fn (AiMessage $m): array => [
                'role' => $m->role === 'assistant' ? 'assistant' : 'user',
                'content' => $m->body,
            ])
            ->values()
            ->all();
    }

    private function systemPrompt(): string
    {
        $path = base_path('ai-assistant/prompts/assistant-conversational-system.txt');
        if (File::isFile($path)) {
            return trim((string) File::get($path));
        }

        return 'Return JSON only for Ask JetPakistan assistant actions.';
    }

    private function openDomainSystemPrompt(): string
    {
        $path = base_path('ai-assistant/prompts/assistant-open-domain-system.txt');
        if (File::isFile($path)) {
            return trim((string) File::get($path));
        }

        return 'For GENERAL_KNOWLEDGE return plain text. For CURRENT_UNVERIFIED return JSON {"message":"...","can_verify_live":false}.';
    }

    /**
     * Accept plain prose for GENERAL_KNOWLEDGE / casual / out-of-domain.
     * If the model still wraps JSON, prefer the message field; otherwise treat
     * prose (including formerly-rejected `{`-prefixed malformed blobs after strip) as text.
     */
    private function extractPlainTextAnswer(string $content): ?string
    {
        $trimmed = trim($content);
        if ($trimmed === '') {
            return null;
        }

        // Optional markdown fence
        if (preg_match('/^```(?:json|text|plaintext)?\s*([\s\S]*?)\s*```$/u', $trimmed, $m) === 1) {
            $trimmed = trim($m[1]);
        }

        $parsed = $this->decodeJsonObject($trimmed);
        if (is_array($parsed)) {
            $reply = trim((string) ($parsed['message'] ?? ''));
            if ($reply !== '') {
                return $reply;
            }
        }

        // Malformed JSON-looking output: try to pull a "message" string without full decode.
        if (preg_match('/"message"\s*:\s*"((?:\\\\.|[^"\\\\])*)"/u', $trimmed, $m) === 1) {
            $pulled = trim(stripcslashes($m[1]));
            if ($pulled !== '') {
                return $pulled;
            }
        }

        // Do not treat unparseable `{...` blobs as plain answers (avoids invalid_json masquerading).
        if (str_starts_with($trimmed, '{')) {
            return null;
        }

        return $trimmed;
    }

    private function extractMessage(string $content): ?string
    {
        $parsed = $this->decodeJsonObject($content);
        if (is_array($parsed)) {
            $reply = trim((string) ($parsed['message'] ?? ''));

            return $reply !== '' ? $reply : null;
        }

        $trimmed = trim($content);
        if ($trimmed === '' || str_starts_with($trimmed, '{')) {
            return null;
        }

        return $trimmed;
    }

    /**
     * Reject model output that looks like tool/action authority rather than an answer.
     */
    private function looksLikeToolOrActionPayload(string $reply): bool
    {
        $lower = mb_strtolower(trim($reply));
        if ($lower === '') {
            return false;
        }

        if (preg_match('/^\s*\{[\s\S]*"(?:tool|tools|action|actions|function|functions|execute_now|authorize)"\s*:/u', $reply) === 1) {
            return true;
        }

        return preg_match(
            '/\b(execute_now|authorize_mutation|supplier_credentials|call_tool|tool_call)\b/u',
            $lower
        ) === 1;
    }

    /**
     * Sanitized structural diagnostics for failed CURRENT/json open-domain parses (no raw body).
     *
     * @param  array<string, mixed>  $result
     * @return array<string, mixed>
     */
    private function sanitizedOpenDomainDiagnostics(string $content, array $result): array
    {
        $trimmed = trim($content);
        $first = $trimmed !== '' ? mb_substr(ltrim($trimmed), 0, 1) : '';
        $last = $trimmed !== '' ? mb_substr(rtrim($trimmed), -1) : '';

        return [
            'RAW_OUTPUT_LENGTH' => mb_strlen($content),
            'RAW_OUTPUT_FIRST_NONSPACE_CHAR' => $first,
            'RAW_OUTPUT_LAST_NONSPACE_CHAR' => $last,
            'HAS_JSON_FENCE' => preg_match('/^```/u', $trimmed) === 1 ? 'YES' : 'NO',
            'HAS_MESSAGE_KEY' => str_contains($content, '"message"') ? 'YES' : 'NO',
            'JSON_DECODE_ERROR_CLASS' => 'invalid_json',
            'FINISH_REASON_IF_PROVIDER_EXPOSES_IT' => $result['finish_reason'] ?? $result['meta']['finish_reason'] ?? null,
            'OUTPUT_TRUNCATED_IF_KNOWN' => ($result['truncated'] ?? $result['meta']['truncated'] ?? null) ? 'YES' : 'NO',
        ];
    }

    /**
     * Reject travel-scope refusals that violate the GENERAL_KNOWLEDGE contract.
     */
    private function isTravelOnlyRefusal(string $reply): bool
    {
        $lower = mb_strtolower(trim($reply));
        if ($lower === '') {
            return false;
        }

        return preg_match(
            '/\b(only (help|assist) (you )?(with )?(flight|travel|booking)|restricted to (flight|travel)|'.
            'cannot answer (this|that|non[- ]?travel)|purpose is to help you with flight|'.
            'travel (bookings?|questions?) only|i (can\'?t|cannot) (help|answer).{0,60}'.
            '(non[- ]?travel|general knowledge|that question)|'.
            'i (am|\'m) (only|just) (a )?travel (assistant|bot)|'.
            'outside (my|the) (travel )?scope)\b/u',
            $lower
        ) === 1;
    }

    /**
     * CURRENT_UNVERIFIED fail-closed gate: require a limitation cue and reject live assertions.
     */
    private function isAcceptableCurrentUnverifiedReply(string $reply): bool
    {
        $lower = mb_strtolower(trim($reply));
        if ($lower === '') {
            return false;
        }

        if (! $this->hasCurrentUnverifiedLimitationCue($lower)) {
            return false;
        }

        if ($this->assertsUnsupportedLiveState($lower)) {
            return false;
        }

        return true;
    }

    private function hasCurrentUnverifiedLimitationCue(string $lower): bool
    {
        return preg_match(
            '/\b(can\'?t|cannot|could not|unable to)\s+(verify|confirm|check|access)\b'.
            '|\b(don\'?t|do not)\s+have\s+(live|current|real[- ]?time)\b'.
            '|\blive\s+(data|market|scores?|prices?|weather|information)\s+(is\s+)?(not|un)available\b'.
            '|\bno\s+(approved\s+)?(live|current|real[- ]?time)\b'.
            '|\bcannot\s+verify\s+(live|current)\b'.
            '|\bwithout\s+(an\s+)?approved\s+live\b'.
            '|\b(live|current)\s+(data|information)\s+isn\'?t\s+available\b/u',
            $lower
        ) === 1;
    }

    private function assertsUnsupportedLiveState(string $lower): bool
    {
        // Numeric / priced live facts.
        if (preg_match('/\$\s?\d|\b\d{2,}\s*(usd|pkr|points|degrees|°)\b/u', $lower) === 1) {
            return true;
        }
        if (preg_match('/\b(currently|right now|as of today)\b.*\b\d/u', $lower) === 1) {
            return true;
        }

        // Qualitative market / stock direction.
        if (preg_match(
            '/\b(trading\s+(higher|lower)|is\s+(up|down)\s+today|rising|falling|gaining|losing)\b'.
            '|\b(stock|share|bitcoin|crypto|market)\b.{0,40}\b(up|down|higher|lower|rally|plunge)\b/u',
            $lower
        ) === 1) {
            return true;
        }

        // Weather state claims.
        if (preg_match(
            '/\b(raining|rainy|sunny|snowing|cloudy|stormy)\b'.
            '|\b(hot|cold|warm|humid)\b.{0,20}\b(right now|today|currently)\b'.
            '|\b(right now|currently|today)\b.{0,30}\b(raining|sunny|snowing|cloudy|hot|cold)\b/u',
            $lower
        ) === 1) {
            return true;
        }

        // Sports live state.
        if (preg_match(
            '/\b(leading|winning|ahead|trailing|drew)\b'.
            '|\bscore\s+is\b|\bwon\s+today\b|\bjust\s+scored\b/u',
            $lower
        ) === 1) {
            return true;
        }

        // Breaking / just-happened news.
        if (preg_match(
            '/\b(has\s+just\s+announced|just\s+announced|breaking\s+news|has\s+happened\s+today|happened\s+today)\b/u',
            $lower
        ) === 1) {
            return true;
        }

        return false;
    }

    /**
     * @return array<string, mixed>|null
     */
    private function decodeJsonObject(string $content): ?array
    {
        $content = trim($content);
        if ($content === '') {
            return null;
        }

        if (preg_match('/\{[\s\S]*\}/', $content, $m) === 1) {
            $content = $m[0];
        }

        try {
            $decoded = json_decode($content, true, 32, JSON_THROW_ON_ERROR);
        } catch (\Throwable) {
            return null;
        }

        return is_array($decoded) ? $decoded : null;
    }
}
